### ISSUE TITLE
time font wrongly wraps wraps

### ISSUE THREAD

**Issue by teras** [pkissling/clock-weather-card#10]
Hello and first of all thank you for this nice widget!
I am using this and under certain sizes, the time wraps and makes this ugly  result.
To make it more clear, I have attached an image.

Is it something that could be done to fix this?

![image](https://user-images.githubusercontent.com/592568/196157216-4345df92-6775-41df-b78c-94615a3468a4.png)

**Comment by pkissling** [comment]
thanks for reporting the issue. i'm able to reproduce the problem using `en` as locale. gonna have a look and provide a fix shortly

**Comment by teras** [comment]
Now it's perfect! Thank you!
