### ISSUE TITLE
Add Vietnamese language

### ISSUE THREAD

**Issue by ngocdungvn** [pkissling/clock-weather-card#104]
> 
#This is the vi.json code of Vietnamese language. Hope the author will update

{
  "weather": {
    "clear-night": "Trời xanh",
    "cloudy": "Nhiều mây",
    "fog": "Sương mù",
    "hail": "Mưa đá",
    "lightning": "Giông bão",
    "lightning-rainy": "Mưa giông",
    "partlycloudy": "Mây rải rác",
    "pouring": "Ẩm ướt",
    "rainy": "Trời mưa",
    "snowy": "Tuyết rơi",
    "snowy-rainy": "Mưa tuyết",
    "sunny": "Trời nắng",
    "windy": "Trời có gió",
    "windy-variant": "Gió mạnh",
    "exceptional": "Khắc nghiệt"
  },
  "day": {
    "0": "Th2",
    "1": "Th3",
    "2": "Th4",
    "3": "Th5",
    "4": "Th6",
    "5": "Th7",
    "6": "CN"
  }
}

**Comment by pkissling** [comment]
hi @ngocdungvn thanks for providing the translations. i don't have access to a laptop for the next 2 months, so i cannot create a pull requests myself. i'd be happily reviewing and approving the pull request, if you create one. cheers
