### ISSUE TITLE
Constant locale console errors

### ISSUE THREAD

**Issue by kylerm42** [pkissling/clock-weather-card#114]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**

Version: 1.0.9

**Last working release (if known):**

**Browser and Operating System:**

Browser: Firefox on Arch
HA: HA Core on Unraid

**Description of problem:**

Without any locale specified in the card config, the console errors below showed up continuously. The readme shows `locale: en` under the "Full Configuration" section, but that produced the same error. It wasn't until changing it to `locale: en-US` when the error stopped appearing. No other functionality seemed affected though.

**Javascript errors shown in the web inspector (if applicable):**

```
clock-weather-card - Locale not supported: en
    getDateFnsLocale clock-weather-card.js:239
    date clock-weather-card.js:239
    renderToday clock-weather-card.js:206
    render clock-weather-card.js:185
```

**Comment by pkissling** [comment]
hi @kylerm42,
thanks for reporting the issue. i will have a look once i'm back from vacation
