### ISSUE TITLE
Adjusting height of current weather stats

### ISSUE THREAD

**Issue by parkerjohn77** [pkissling/clock-weather-card#116]
The current weather and clock are the first things I look at on the screen.  Could you make them both adjustable?

Also, dumb question, but what do the colored sections mean on the forecast for each day?

**Comment by Feherfy** [comment]
I had problem with the texts sizes too, and I fixed with Card-Mod.

For example:
`card_mod:
  style: |
    clock-weather-card-today-right-wrap-top {
    font-size: 25px;
    }
    clock-weather-card-today-right-wrap-bottom {
    font-size: 20px;
    }
`

**Comment by pkissling** [comment]
hi @parkerjohn77, i'd as well propose to use card-mod to customise the card to your liking.

**Comment by Feherfy** [comment]
@pkissling another, but connecting topic: do you think can I somehow edit the decimals of the shown temperatures by card-mod?

**Comment by pkissling** [comment]
i don't think so. what do want to do exactly?

**Comment by Feherfy** [comment]
> i don't think so. what do want to do exactly?

Just add decimal points, so it doesn’t just show the whole integer values.

**Comment by parkerjohn77** [comment]
> 
Thank you much!

**Comment by pkissling** [comment]
> > i don't think so. what do want to do exactly?
> 
> 
> 
> Add decimal points, so it doesn’t just show the whole integer values.

this request was already raised via #111 - maybe you can leave a thumbs up there.
please note that i'm currently on vacation. hence I will be able to work on the code starting January next year
