### ISSUE TITLE
While installing, HASS says not to put resources in ui-lovelace.

### ISSUE THREAD

**Issue by jsantosdias** [pkissling/clock-weather-card#119]
While installing, HASS says not to put resources in ui-lovelace, but instead on panel configuration... There, it's all different and Wheather Clock already there... Where should I put resources? What should I do? Either way, I can't put this to work as always appears: No visual editor for type....

**Comment by pkissling** [comment]
clock-weather-card does not have a visual editor. did you follow the [installation instructions](https://github.com/pkissling/clock-weather-card#installation-and-tracking-with-hacs)?

**Comment by Santanachia** [comment]
1. @jsantosdias doesn't write about adding a card visually, but about adding a resource
2. the installation instructions are faulty. There is no way to add a resource via YAML, you can only add it through the GUI
![image](https://user-images.githubusercontent.com/4628507/203501158-669d6cfd-cd77-4ac1-87b0-367897b1a7e6.png)
![image](https://user-images.githubusercontent.com/4628507/203501283-c3f3ce04-105a-4f71-a265-b6b75d83b049.png)
![image](https://user-images.githubusercontent.com/4628507/203501397-74203e65-4385-42b2-a8a4-fc49f4bca1a3.png)

**Comment by jsantosdias** [comment]
Yes, that's exactly that! Thank you! What should I do?

**Comment by Santanachia** [comment]
don't know. It doesn't work for me either. I'm hoping @pkissling will adjust the instructions to how Home Assistant currently works.

**Comment by pkissling** [comment]
i'm currently on vacation and don't even have a laptop with me. to me it's not clear what this issue is caused by (maybe a change in a recent HA release?). i'm afraid this issue has to wait until january unless somebody of you is willing to dig into the issues
