### ISSUE TITLE
not working anymore (climacell)

### ISSUE THREAD

**Issue by dominickdm** [pkissling/clock-weather-card#123]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser
- [X] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:** 1.0.9

**Last working release (if known):** 1.0.9

**Browser and Operating System:** Windows and Mac with Chrome

**Description of problem:**
Since this morning, the clock weather card is not showing up anymore on my dashboard.

![image](https://user-images.githubusercontent.com/40289256/203847304-4fb59ff1-841c-43ea-8467-f882ea992003.png)

Yaml config:
![image](https://user-images.githubusercontent.com/40289256/203847706-fda0540c-29d3-4c4b-9eac-2c092cab53f1.png)

I use climacell as input, the entitity is available

![image](https://user-images.githubusercontent.com/40289256/203847513-8ea18d00-de4e-4cec-9638-91c429e810c2.png)

Any idea what broke it suddenly?

**Javascript errors shown in the web inspector (if applicable):**

![image](https://user-images.githubusercontent.com/40289256/203847433-71db794c-7531-4c1f-9583-a7d9f8f5178b.png)
```

```

**Additional information:**

**Comment by pkissling** [comment]
hi @dominickdm I currently don't have access to a computer, hence cannot investigate the issue.
my hunch is that your data provider delivers some data in an unexpected fashion.
can please provide me your weather provider and the corresponding weather location?
i will try to reproduce and possibly fix the issue when i'm back from vacation in January.

furthermore it would be helpful if you could dump the weather state (all attributes) at the exact moment when the weather card breaks

**Comment by dominickdm** [comment]
Hello @pkissling,

Thank you for your reply and enjoy your vacation.

I'm using climacell (Tomorrow.io) (https://www.home-assistant.io/integrations/tomorrowio), forecast type 'daily' on location 'Zingem' (not sure where to find the actual configured location..).

Here is the export of all attributes:

temperature_unit: °C
pressure_unit: hPa
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast:
  - datetime: '2022-11-25T05:00:00+00:00'
    condition: sunny
    precipitation_probability: 0
    wind_bearing: 220.88
    temperature: 11
    templow: 4.5
    wind_speed: 19.58
    precipitation: 0
  - datetime: '2022-11-26T05:00:00+00:00'
    condition: cloudy
    precipitation_probability: 5
    wind_bearing: 179.02
    temperature: 9
    templow: 4.6
    wind_speed: 18.32
    precipitation: 0
  - datetime: '2022-11-27T05:00:00+00:00'
    condition: rainy
    precipitation_probability: 100
    wind_bearing: 172
    temperature: 7.5
    templow: 5.8
    wind_speed: 23.44
    precipitation: 23.04
  - datetime: '2022-11-28T05:00:00+00:00'
    condition: rainy
    precipitation_probability: 85
    wind_bearing: 229.76
    temperature: 7.5
    templow: 4.3
    wind_speed: 21.17
    precipitation: 10.08
  - datetime: '2022-11-29T05:00:00+00:00'
    condition: sunny
    precipitation_probability: 5
    wind_bearing: 264.56
    temperature: 9.3
    templow: 3.5
    wind_speed: 13.14
    precipitation: 0.96
  - datetime: '2022-11-30T05:00:00+00:00'
    condition: cloudy
    precipitation_probability: 5
    wind_bearing: 146.62
    temperature: 7.7
    templow: 1.9
    wind_speed: 11.16
    precipitation: 0.96
  - datetime: '2022-12-01T05:00:00+00:00'
    condition: cloudy
    precipitation_probability: 0
    wind_bearing: 52.03
    temperature: 6.2
    templow: 1.8
    wind_speed: 20.3
    precipitation: 0
  - datetime: '2022-12-02T05:00:00+00:00'
    condition: cloudy
    precipitation_probability: 0
    wind_bearing: 78.68
    temperature: 6.4
    templow: 1.3
    wind_speed: 7.09
    precipitation: 0
  - datetime: '2022-12-03T05:00:00+00:00'
    condition: cloudy
    precipitation_probability: 5
    wind_bearing: 108.11
    temperature: 6
    templow: 1.1
    wind_speed: 11.95
    precipitation: 0.24
  - datetime: '2022-12-04T05:00:00+00:00'
    condition: cloudy
    precipitation_probability: 20
    wind_bearing: 144.94
    temperature: 10
    templow: 5.8
    wind_speed: 26.71
    precipitation: 0.48
  - datetime: '2022-12-05T05:00:00+00:00'
    condition: cloudy
    precipitation_probability: 0
    wind_bearing: 131.48
    temperature: 11.3
    templow: 5.8
    wind_speed: 24.34
    precipitation: 0
  - datetime: '2022-12-06T05:00:00+00:00'
    condition: cloudy
    precipitation_probability: 0
    wind_bearing: 90.07
    temperature: 7.5
    templow: -0.5
    wind_speed: 18.72
    precipitation: 0
  - datetime: '2022-12-07T05:00:00+00:00'
    condition: sunny
    precipitation_probability: 0
    wind_bearing: 64.87
    temperature: 2.3
    templow: -3.3
    wind_speed: 20.48
    precipitation: 0
  - datetime: '2022-12-08T05:00:00+00:00'
    condition: sunny
    precipitation_probability: 0
    wind_bearing: 61.01
    temperature: 0.7
    templow: -5
    wind_speed: 24.52
    precipitation: 0
attribution: Powered by Tomorrow.io
friendly_name: ClimaCell - Daily

**Comment by dominickdm** [comment]
It might be related to the current temperature, since the current weather temperature shows NaN?

![image](https://user-images.githubusercontent.com/40289256/203979354-c5bf503b-f219-4944-86aa-65f8b77bb47c.png)

**Comment by pkissling** [comment]
yeah, thats possible. the card relies on a temperature attribute, which (sometimes) does not exist for your weather provider.

i will create a bug fix to make sure that the card still properly renders if `temperature` is not delivered by the provider. thanks for the hint

ETA is mid january
