### ISSUE TITLE
Wheater icons without internet

### ISSUE THREAD

**Issue by remcomeer89** [pkissling/clock-weather-card#124]
Love the clock-weather-card,
but i also like my wall tablet to be disconnected from the internet.

At the moment the weather icons only work with an active internet connection.

Would like to see a way to point to local icons, as they are easy to download from the basmilius github.

**Comment by pkissling** [comment]
i'll consider this a bug although the behaviour you describe should work, since the icons are part of the js bundle and hence should be available offline.

since i'm on vacation i cannot reproduce - analyse the issue. 

this issue will have to wait until  Jan

**Comment by pkissling** [comment]
can you post a screenshot of the card without internet connection?

**Comment by remcomeer89** [comment]
![IMG_20221130_064026184_HDR](https://user-images.githubusercontent.com/56893286/204908779-b071053b-bfb2-4103-b314-df65f827d808.jpg)

**Comment by remcomeer89** [comment]
Can't seem to recreate the problem. Connected the tablet to the internet. At that point the icons showed up right away. After disconnecting from the internet they ware still working! Think once they are in browser cache they are working fine offline. Have a nice holiday!

**Comment by pkissling** [comment]
just to make sure we talk about the same thing - the icons you highlighted are not from my clock-weather-card

**Comment by pkissling** [comment]
hi @remcomeer89, is this issue still relevant? if yes, could you please answer my previous question?

**Comment by pkissling** [comment]
closing due to lack of response and clarity

**Comment by remcomeer89** [comment]
@pkissling Sorry not being able to contact sooner. When i read your message don't know if i should cry or not. before contacting i was looking if i could fix this myself. But never realising i was looking at te wrong card! your card is the one at the top and not the bottom.. and your card worked flawless without internet! sorry to bother you. have a nice holiday, think i need one myself..
