### ISSUE TITLE
Double digit negative temperatures get cut off in forecast

### ISSUE THREAD

**Issue by JustSid** [pkissling/clock-weather-card#125]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
1.0.9

**Browser and Operating System:**
Firefox on Windows and macOS, Safari on iOS.

**Description of problem:**

We have minus degrees here and with double digit negative degrees, the unit symbol gets cut off in the forecast view. See this screenshot:
![image](https://user-images.githubusercontent.com/301144/204897160-e6d8599e-8525-4c9e-a08f-606e6f764200.png)

**Comment by pkissling** [comment]
hi @JustSid thanks for reporting the issue. will fix it after my vacation in January
