### ISSUE TITLE
Day and night icon not working after HA restart

### ISSUE THREAD

**Issue by pepe59** [pkissling/clock-weather-card#127]
I couldn't find an option to open an already closed issue, so I'm opening it again.
If I don't restart HA after sunset, the night icon works.
If I restart HA after sunset it loads the day icon which lasts until the next sunset and switches to night mode until I restart HA after sunset it repeats again.

**Comment by pkissling** [comment]
thanks for reporting. i'll have a look after my vacation

**Comment by pkissling** [comment]
hi @pepe59, i want to reproduce the issue you describe, but i'm not able to. 
can you please provide the necessary steps?

what i did: 
1. wait until sunset (sun entity has state `below_horizon`)
2. restart HA
3. wait until dashboard reloads upon restart
4. expected day icon (as per issue), but was actually night

do you provide a custom sun entity?

**Comment by pepe59** [comment]
Current status.
See the time, icon and status of the entity
![karta pocasi pod obzorem](https://user-images.githubusercontent.com/61280529/211216412-401d924a-84f7-4b13-9ce6-73271f2785aa.png)
![nastaveni karty pocasi](https://user-images.githubusercontent.com/61280529/211216453-ac1db4d9-065f-4c65-8fcb-2b4fde4025a3.png
![stav entity sun_sun](https://user-images.githubusercontent.com/61280529/211216495-fd2d2003-4856-4392-95c7-6e5e3332d065.png)
![sun pod obzorem](https://user-images.githubusercontent.com/61280529/211216523-0616e9a2-83cf-4c1d-aa02-d33c89972597.png)

**Comment by pkissling** [comment]
thanks for the feedback.
although i cannot reproduce the issue, i have a hunch on what is going wrong.
i created a build containing a potential bugfix. would you kindly test the build to see if this resolves the issue?
additionally I added some log statements in the console, so i'd appreciate a screenshot of your developer console when testing the fix (upon restarting
[clock-weather-card.js.zip](https://github.com/pkissling/clock-weather-card/files/10375872/clock-weather-card.js.zip)
 HA)

**Comment by pepe59** [comment]
I unzipped the zip files and copied everything to /config/www/community/clock-weather-card
I have restarted HA and the night icon is showing correctly after the restart.
Thank you
I would like to get the protocol you require, but I have no idea how or where to get it. Could you give me a push?
There is no weather card error in the HA log.

**Comment by pkissling** [comment]
thanks for the feedback.
what you are looking at is the right tool (browser console). 

though i am not looking for error messages, but info messages to allow me understand the status of your sun entity:
![image](https://user-images.githubusercontent.com/33731393/211523053-bfcf6cd3-9c29-4b1d-b454-361e748c0780.png)

**Comment by pepe59** [comment]
I have no idea if I'm doing something wrong.
I've tried your procedure several times and the only information worth it is here
![snimek konzole karta pocasi](https://user-images.githubusercontent.com/61280529/211615603-8bca1df3-5589-4468-96d6-0b10af7a5713.png)

**Comment by pkissling** [comment]
seems like you didn't reload the resources in HA after installation. the version I provided should be `0.0.0`.
but nevermind - since the fix appears to be working, i'm happy to close the ticket and include the fix in the next release
