### ISSUE TITLE
Blank Card | AccuWeather

### ISSUE THREAD

**Issue by gamajunior** [pkissling/clock-weather-card#128]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser
- [X] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
1.0.9
**Last working release (if known):**
NA
**Browser and Operating System:**
Win 10 | Chrome

**Description of problem:**
I installed it via hacs, and put in the AccuWeather weather entity, but the card is blank.

![1](https://user-images.githubusercontent.com/78893093/206352025-a07e059d-5948-4782-bbff-62e871a00bee.png)
![2](https://user-images.githubusercontent.com/78893093/206352052-cf938fb5-65c8-4bc5-b058-f3775e9f6fdf.png)
![3](https://user-images.githubusercontent.com/78893093/206352070-96856fea-3fed-4c26-8a29-22a3797f60a5.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by pkissling** [comment]
hi @gamajunior, is this issue still relevant?
