### ISSUE TITLE
Change size or switch position of Clock and current Temperature.

### ISSUE THREAD

**Issue by juleztb** [pkissling/clock-weather-card#141]
I'd like to change the size of the clock and the current temperature. Most times I use my Dashboard to get information, that I don't have immediately available anywhere else. The Clock usually is available on other walls or my wrist. The current temperature isn't.
So I'd like to be the temperature easily readable, rather than the clock.

Already tried realizing this with other cards, but non are as beautiful as yours.

**Comment by pkissling** [comment]
hi @juleztb,

thanks for reporting the issue.
there is a PR (#131) from @jlambert121 which does exactly what you ask for.
haven't had the time to review the PR, yet. will try to review and possible merge it next week

**Comment by pkissling** [comment]
Resolved via #131
