### ISSUE TITLE
Day/night fuctionality not working for weather state "sunny"

### ISSUE THREAD

**Issue by cromelex** [pkissling/clock-weather-card#145]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser
- [ X] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
1.0.10

**Last working release (if known):**

**Browser and Operating System:**
Chrome, Firefox on Windows 10
Chrome on Android
Webview on NestHub

I have noticed that whenever the weather entity is in state "sunny" (which happens even during the night period, the icon does not change as per the day/night functionality.
I do not think my issue is with the sun_entity as it works perfectly for other states (ie, "partlycloudy") where I am seeing the moon icon etc.

I have my card configured as:
```
type: custom:clock-weather-card
entity: weather.home
sun_entity: sun.sun
weather_icon_type: line
animated_icon: true
forecast_days: 5
```
Even though the sun is below horizon, "sunny" still renders the day icon - I would expect a moon, night icon instead?

I have tried two different weather integrations and I get the same result nevertheless - they both seem to return sunny regardless of the time of day.

![weather clock](https://user-images.githubusercontent.com/96779452/214649954-a0621b60-aace-4491-b8de-98a9a0e55bfd.JPG)

Thanks in advance

**Comment by meshkat200198** [comment]
I have the same issue described by @cromelex . Also, I've noticed the "dot indicator" does not display.  Judging by the screenshot it seems that @cromelex is having the same issue with the "dot indicator".

**Comment by cromelex** [comment]
> I have the same issue described by @cromelex . Also, I've noticed the "dot indicator" does not display. Judging by the screenshot it seems that @cromelex is having the same issue with the "dot indicator".

I think the dot indicator is related to the weather provider not providing "today" in the forecast section. I think it is somewhere in the FAQ that if you use openweather for example they do provide it and therefore you should be able to see the "dot" indicator.

**Comment by pkissling** [comment]
hi @cromelex and @meshkat200198,
issue is fixed. thanks for reporting the bug. 
it did not cross my mind that a weather provider will report 'sunny' during night - especially since home assistant has a weather state `clear-night` for that case.

**Comment by meshkat200198** [comment]
Thank you @cromelex for the suggestion. I changed my weather provider and now the "dot indicator" is working properly. Thank you @pkissling for the quick fix but my sun icon is sitll not changing. I've re-downloaded from HACS and have re-started my HA. Any suggestions on what I need to do?

**Comment by pkissling** [comment]
you have to wait some days until the fix is released. i'll wait a couple of days to bundle multiple changes in one release
