### ISSUE TITLE
Hide Clock and Hide Date options do not seem to work

### ISSUE THREAD

**Issue by poxin13** [pkissling/clock-weather-card#147]
Not able to get the current temp to display instead of the clock, otherwise it looks great! Would love to see an option for Temp & Humidity is larger letters.

![image](https://user-images.githubusercontent.com/10375741/215896952-e581c6a6-3ad9-42e2-9641-04c022183ca3.png)

**Comment by marcis92** [comment]
I'm facing the same issue

![image](https://user-images.githubusercontent.com/76939141/216008039-d27ec499-4e43-4889-b771-efa48f781c9b.png)

**Comment by pkissling** [comment]
sorry, it was due to the fact that the latest version containing the feature was not yet released.
i released it just now: https://github.com/pkissling/clock-weather-card/releases/tag/1.0.11
