### ISSUE TITLE
Card Empty

### ISSUE THREAD

**Issue by Soulsedge** [pkissling/clock-weather-card#148]
Hi ! 

I'm running Home Assistant & Package last version but when I place the custom clock weather card it's appear empty

![image](https://user-images.githubusercontent.com/77757445/216165441-1a169fdb-8099-40a4-bef4-cd6afa79d78c.png)

I already try to change the weather source with AccuWeather but changed nothing

![image](https://user-images.githubusercontent.com/77757445/216165841-0f4b700b-fd39-48c9-9e19-3a747d19a84f.png)

I also check the ressource manager with the correct url & type
![image](https://user-images.githubusercontent.com/77757445/216165927-72726048-b7b6-4416-b20e-cee7cbb524c4.png)

I don't really if I miss something or if it's a bug but I prefer report it

**Comment by pkissling** [comment]
hi, thanks for reporting the issue. can you post the output of your browser console?

**Comment by Soulsedge** [comment]
With the both entity sun & weather I have the same output

![image](https://user-images.githubusercontent.com/77757445/216293744-92901ec8-9f11-46cf-b6ac-6430e2e70933.png)

**Comment by Soulsedge** [comment]
Ok with the entity: weather.forecast_maison it's works.
My bad and thanks for the help
