### ISSUE TITLE
Resize with lovelace cards

### ISSUE THREAD

**Issue by telegrambeans** [pkissling/clock-weather-card#150]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser
- [x ] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
Latest
**Last working release (if known):**
Idk
**Browser and Operating System:**
Fully Kiosk Browser and companion app

**Description of problem:**

The card dont resize with other cards in grid or horizontal-stack. 
So you can not create a uniform interface. i use the panel option. 

![IMG_20230205_142730](https://user-images.githubusercontent.com/13040847/216821935-e9f8cde3-da19-49d3-908b-01dea1487d40.png)

![IMG_20230205_143202](https://user-images.githubusercontent.com/13040847/216822104-82175535-f783-4371-b97c-1f5db863004d.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by pkissling** [comment]
Thanks for reporting the issue. a fix will be included in the upcoming release
