### ISSUE TITLE
Change Custom current Temperature

### ISSUE THREAD

**Issue by HybridRCG** [pkissling/clock-weather-card#152]
Hi

I have a Weather Station that I can Pull sensors from.. IE , current temp, current rain, wind etc. 

Would be great to be able to substitute some of the items in the card..

Would love to be able to use my sensor.currenttemp in place of the temp received from weather.home

**Comment by pkissling** [comment]
there is already a PR pending for this. haven't found the time to verify on my HA instance though.
https://github.com/pkissling/clock-weather-card/pull/103

**Comment by HybridRCG** [comment]
Thanks, Thought It might have been forgotten about. :) , Bu tI see you were on holiday. :) , Hope to see the new Release soon.  :)

**Comment by pkissling** [comment]
I reviewed the PR. waiting for changes :)

**Comment by HybridRCG** [comment]
Sorry, Im new to this. Must I do something? :)

**Comment by pkissling** [comment]
all good. i'll inform you when the  PR is merged

**Comment by HybridRCG** [comment]
maybe a beta for tasting? :) , My Wife says my dashboard looks ugly now that i don't use your Card. :)

**Comment by HybridRCG** [comment]
I have not seen the update? Sorry noob here. 😩

**Comment by pkissling** [comment]
an update will be released in the next few days. i am waiting #102 to be merged

**Comment by pkissling** [comment]
i just released 1.0.12 with this feature included

**Comment by HybridRCG** [comment]
Thank you. Best RegardsRiaanOn 03 Mar 2023, at 20:49, Patrick Kissling ***@***.***> wrote:﻿
i just released 1.0.12 with this feature included
