### ISSUE TITLE
No bars in forecast

### ISSUE THREAD

**Issue by aLAN-LDZ** [pkissling/clock-weather-card#153]
Hi

How to enable bars? I copy all config from readme and i dont have bars :(

![image](https://user-images.githubusercontent.com/33158372/218329844-ec4c9ded-b7b5-49e5-8be1-b36b80621b50.png)

**Comment by pkissling** [comment]
hi @aLAN-LDZ,
the bars should be visible by default. i assume there is some issue with the data provided by your weather provider. which provider are you using?
furthermore, can you check the developer console to see if there is an exception in the logs?

**Comment by aLAN-LDZ** [comment]
I solved the problem, it was about the size of the card - it was just too small
