### ISSUE TITLE
What do the areas inside the bars represent?

### ISSUE THREAD

**Issue by dahlma** [pkissling/clock-weather-card#159]
Hi! I feel like an idiot but I have to ask,

the (in my case) lighter colored areas inside a days forecast, what do the represent?

The question goes also for the little white dot that’s moving around…

![E6ADCB7F-E29B-49E4-8264-954FB88C0528](https://user-images.githubusercontent.com/15905382/221774245-68ed69ad-2b79-4605-b83b-29df198b48a8.jpeg)

**Comment by pkissling** [comment]
hi @dahlma,
i added a dedicated FAQ entry to address your question. do you find it sufficient?

**Comment by dahlma** [comment]
Super, thanks for the explanation!
