### ISSUE TITLE
Day name displayed twice if `PPPP` is used as `date_pattern`

### ISSUE THREAD

**Issue by bieniu** [pkissling/clock-weather-card#163]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**

1.0.12

**Last working release (if known):**

**Browser and Operating System:**

Windows, Firefox/iOS, companion app

**Description of problem:**

If `date_pattern` is `PPPP`, the card displays the day name twice: `Sat, Sarurday, March 4th, 2023`

![obraz](https://user-images.githubusercontent.com/478555/222892395-c6409a1d-573c-4f26-b75f-ff98ab00bd6b.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by pkissling** [comment]
Duplicates #89
