### ISSUE TITLE
First date is not tomorrow but today

### ISSUE THREAD

**Issue by bigboban** [pkissling/clock-weather-card#171]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser
- [x ] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
1.0.13

**Last working release (if known):**
?

**Browser and Operating System:**
Chrome

**Description of problem:**
First line of forecast is today not tomorrow. I expect tomorrow on first line because it is FORECAST. Today should be (and it is) on top and it is hidable using "hide_today_section".

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
I use open-weather-map weather entity.

Yes i read "Why don't I see the current day in my weather forecast?" FAQ. And i expect NOT to see today in forecast as right behavior.

**Comment by pkissling** [comment]
i'd argue that a forecast contains the weather from now on into the future. and this means that todays weather is part of the forecast and hence should be displayed accordingly
