### ISSUE TITLE
showing location

### ISSUE THREAD

**Issue by haitonno** [pkissling/clock-weather-card#173]
**Is your feature request related to a problem? Please describe.**
Im actualy on a Trip through Europe with my Mobile Home using home assistant as Control center. I dont know, which Location is actualy used for forecast (home location?).
**Describe the solution you'd like**
Showing the Location in the weather card. configurable by show_location: true / false
Maybe making the used Location configurable by location: zipcode (of the country)

**Describe alternatives you've considered**

**Additional context**

**Comment by pkissling** [comment]
hi @haitonno, have you considered using the `title` property in the card for your use case?

**Comment by pkissling** [comment]
i'll close this issue as i suggest using the `title` property for your use case

**Comment by haitonno** [comment]
so it‘s not. but now i understand, that location is fix and set once at setup. I‘m at serveral places with my mobilehome and need the actual location, were i stay. thats another itemAm 22.04.2023 um 17:31 schrieb Patrick Kissling ***@***.***>:﻿
i'll close this issue as i suggest using the title property for your use case
