### ISSUE TITLE
Allow a sensor for the date/time

### ISSUE THREAD

**Issue by rad2000** [pkissling/clock-weather-card#180]
**Is your feature request related to a problem? Please describe.**
New feature forked from https://github.com/pkissling/clock-weather-card/issues/157

**Describe the solution you'd like**
Currently, a user can specify any sensor for the temperature and forecast. This gives them the ability to show the weather in a different timezone. The request here is to allow something similar for the date/time so that the user can show the date/time for the same timezone as the weather.
A sample use case, I have 6 weather cards displayed on my wall for timezones where I have relatives. But currently, I can only show the HA server or browser time with each weather card. The ask is to be able to specify any date/time sensor so that I can show the matching date/time.

**Describe alternatives you've considered**
Using another weather card or pairing a different date/time card with this weather card and hiding the date/time from the weather card.

**Additional context**
Not a critical feature as I'll likely do the alternative as described above, but it would be nice as it would allow consistency and a nicer look. Thanks for considering and thanks for this card!

**Comment by pkissling** [comment]
will be done via #197
