### ISSUE TITLE
Add "strong winds" icon

### ISSUE THREAD

**Issue by zaid3ssaf** [pkissling/clock-weather-card#184]
Using the National Weather Service (NWS)  integration. When the weather status is 'strong winds' the card shows no icon. Thanks

**Comment by pkissling** [comment]
hi @zaid3ssaf, 
according to the official home assistant documentation, there is no such weather condition as "strong winds". can you please point me the direction on where this weather conditions originates from...?
https://www.home-assistant.io/integrations/weather/
https://github.com/home-assistant/core/blob/5f7496f97bbc976141e0e959f6debd5bbf3a5ed6/homeassistant/components/weather/__init__.py#L68
