### ISSUE TITLE
Please add support for Estonian language

### ISSUE THREAD

**Issue by holger1414** [pkissling/clock-weather-card#186]
Would gladly help with translations.

**Comment by pkissling** [comment]
hi @holger1414,

sure thing. can you please translate the following json to Estonian?
https://raw.githubusercontent.com/pkissling/clock-weather-card/master/src/localize/languages/en.json

**Comment by holger1414** [comment]
Here you go!

{
  "weather": {
	"clear-night": "Selge",
	"cloudy": "Pilvine",
	"fog": "Udu",
	"hail": "Rahe",
	"lightning": "Äike",
	"lightning-rainy": "Äiksevihm",
	"partlycloudy": "Vahelduv pilvisus",
	"pouring": "Paduvihm",
	"rainy": "Vihm",
	"snowy": "Lumi",
	"snowy-rainy": "Lörts",
	"sunny": "Päike",
	"windy": "Tuuline",
	"windy-variant": "Tuuline",
	"exceptional": "Äärmuslik"
},
  "day": {
	"0": "P",
	"1": "E",
	"2": "T",
	"3": "K",
	"4": "N",
	"5": "R",
	"6": "L"
  }
}
