### ISSUE TITLE
Make day of the week part of the date pattern

### ISSUE THREAD

**Issue by mleiber** [pkissling/clock-weather-card#190]
**Is your feature request related to a problem? Please describe.**
As there is already the possibility to customize the date display it would be beneficial to also define the format of the day of the week in this pattern. Right now it seems to be hard coded (resp. follows the locale) to a 3 char abbreviation.

**Describe the solution you'd like**
Once the date_pattern os specified by the user remove the fixed week of the day display and let the user select which format as part of the date_pattern.

**Describe alternatives you've considered**
No alternative available.

**Additional context**

**Comment by pkissling** [comment]
duplicates #89
