### ISSUE TITLE
Hourly forecast is wrong

### ISSUE THREAD

**Issue by kevtuning** [pkissling/clock-weather-card#191]
Hi everyone, 

I am a new user... and I am not able to display correctly the Hourly forecast (see details below)

**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser
- [x ] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:** 1.0.16

**Last working release (if known):** N/A new user

**Browser and Operating System:** tested on Win 10 Chrome and iOS Companion app

**Description of problem:**

I try to display hourly forecast.... but it display a daily forecast for 12:00 (see screnshot: on top daily forecast ; below hourly_forecast: true)

![image](https://github.com/pkissling/clock-weather-card/assets/5998776/11f40a2d-0aec-4168-8efa-a3ac28ee8b48)

Configuration;

![image](https://github.com/pkissling/clock-weather-card/assets/5998776/945ec6a5-dd0f-4754-9f01-b1e1f399ed22)

**Additional information:**

**Comment by pkissling** [comment]
hi @kevtuning,
this only works if your weather provider delivers hourly forecasts
