### ISSUE TITLE
Bars overlapping low temp unit on Android in HA app.

### ISSUE THREAD

**Issue by LeiChat** [pkissling/clock-weather-card#194]
clock-weather-card v.1.0.16
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

Android 13.
HA app v.2023.7.5-full

![Screenshot_2023-07-14-18-20-01-55_c3a231c25ed346e59462e84656a70e50](https://github.com/pkissling/clock-weather-card/assets/23559551/8c4a69ad-188b-4903-beb9-45f7b8a4aa0a)

**Comment by pkissling** [comment]
i am not able to reproduce the issue - i don't have an android device avaialble

**Comment by LeiChat** [comment]
No worries. It is not a significant issue.
