### ISSUE TITLE
Hourly temperature forecast

### ISSUE THREAD

**Issue by Santanachia** [pkissling/clock-weather-card#200]
if the forecast is hourly in the source data, let's show hourly and not delete the data
![image](https://github.com/pkissling/clock-weather-card/assets/4628507/e8213578-9121-42b9-839f-08a38c1b2e15)
![image](https://github.com/pkissling/clock-weather-card/assets/4628507/3f0db090-b8d1-466e-9a52-764304d8923c)
Maybe instead of bars, make a line graph?

**Comment by pkissling** [comment]
hey @Santanachia,

if you want to display hourly data, you have to set the corresponding option `hourly_forecast: true` in the settings.
please refer to https://github.com/pkissling/clock-weather-card#options
