### ISSUE TITLE
Won 't work

### ISSUE THREAD

**Issue by VenimK** [pkissling/clock-weather-card#202]
<img width="1056" alt="Scherm­afbeelding 2023-09-10 om 05 53 50" src="https://github.com/pkissling/clock-weather-card/assets/666520/6dff81dd-c593-4dc4-a253-6b3ca1204151">

Installed via HACS
Added card in gui, but keeps spinning ???

**Comment by pkissling** [comment]
you must note use an array when configuring via UI
