### ISSUE TITLE
Card doesn't work for DWD (Deutscher Wetterdienst) any more

### ISSUE THREAD

**Issue by arboeh** [pkissling/clock-weather-card#206]
**Checklist:**

- [x] I updated to the latest version available
- [X] I cleared the cache of my browser
- [X] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
1.0.17

**Last working release (if known):**

**Browser and Operating System:**
Chrome, Windows 11

**Description of problem:**
Integration 'Deutscher Wetterdienst - DWD' had a big refactoring update yesterday from V1.2.28 to V2.0.0 and now the clock weather card doesn't work any more, because the forecast attribute is missing.
I know that normally it is 'problem' of the weather card integration (see also https://github.com/FL550/dwd_weather/issues/77)", but the service seems to has forecast values:

![flameshot_2023-09-22_07-40](https://github.com/pkissling/clock-weather-card/assets/12322114/914a7dd2-25ee-47b5-ab0e-dacea023d1cf)

**Javascript errors shown in the web inspector (if applicable):**

```
clock-weather-card.js?hacstag=5226340191017:172 clock-weather-card - Error while rendering clock-weather-card component: Error: Weather entity does not have attribute "forecast".
    at Iw.getWeather (clock-weather-card.js?hacstag=5226340191017:240:2440)
    at Iw.renderForecast (clock-weather-card.js?hacstag=5226340191017:210:72)
    at clock-weather-card.js?hacstag=5226340191017:190:30
    at vn (clock-weather-card.js?hacstag=5226340191017:172:218135)
    at Iw.render (clock-weather-card.js?hacstag=5226340191017:190:17)
    at Iw.update (clock-weather-card.js?hacstag=5226340191017:23:405)
    at Iw.performUpdate (clock-weather-card.js?hacstag=5226340191017:11:5057)
    at Iw.scheduleUpdate (clock-weather-card.js?hacstag=5226340191017:11:4704)
    at Iw._$EC (clock-weather-card.js?hacstag=5226340191017:11:4612)
```

**Additional information:**
Attributes from DWDs service:
```
temperature: 14.5
temperature_unit: °C
humidity: 87
pressure: 1000.8
pressure_unit: hPa
wind_bearing: 205
wind_speed: 16.7
wind_speed_unit: km/h
visibility: 19.1
visibility_unit: km
precipitation_unit: mm
latest_update_utc: '2023-09-22T05:20:53.959346+00:00'
report_time_utc: ''
forecast_time_utc: '2023-09-22T03:00:00+00:00'
station_id: XXXX
station_name: XXXXXXXXXX
attribution: Data provided by Deutscher Wetterdienst (DWD)
friendly_name: XXXXXXXXXX
supported_features: 3
```

**Comment by arboeh** [comment]
Sorry, guess it's a duplicate of https://github.com/pkissling/clock-weather-card/issues/203 and it's in content with https://github.com/pkissling/clock-weather-card/issues/204 also.

**Comment by FL550** [comment]
See here for reference: [Weather attribute](https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service)

**Comment by pkissling** [comment]
duplicates #203
