### ISSUE TITLE
Change Colour Of Rain Drops

### ISSUE THREAD

**Issue by Stuartyboy75** [pkissling/clock-weather-card#207]
**Describe the solution you'd like**
Hi

I have the weather clock card installed and its great, The only thing i would like and its because i have a dark theme on tablet i cannot see the rain drops between day and temperature.

So i was wondering is there a way to change colour ?

Thanks

Stuart

![Weather Icon](https://github.com/pkissling/clock-weather-card/assets/126591323/d79d5424-687d-4808-a306-6e8978c6179a)

**Comment by pkissling** [comment]
will be tracked via #203
