### ISSUE TITLE
Tommorow.io hourly forecast not working

### ISSUE THREAD

**Issue by thewan056** [pkissling/clock-weather-card#218]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:** 1.1.0

**Last working release (if known):**

**Browser and Operating System:** Edge on Windows 11

**Description of problem:**
Hourly forecasts using [Tommorow.io](https://www.home-assistant.io/integrations/tomorrowio/) does not work.

<img width="904" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/24851051/b7b4563a-8426-4c26-844e-3f210d4b58ae">

It does have both daily and hourly weather:

<img width="507" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/24851051/f357416e-613a-48c2-86a9-d351030615d9">

The HA weather card works fine:

<img width="906" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/24851051/69cbe68c-200a-4560-8bdf-bb0b8ec8b4c1">

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Santanachia** [comment]
@pkissling Weather.com integration no longer support `forecast` attribute

**Comment by Rehold** [comment]
> thanks for reporting the issue. problem is related to the fact that although Tomorrow.io supports `weather.get_forecast` they still supply the deprecated `forecast` attribute. clock-weather-card is currently implemented in a way that it tries to read `forecasts` and only if this attribute does not exist, it subscribes to `weather.get_forecast`. i think i have to change the logic on how the card identifies whether the current entities supports `weather.get_forecast`. ![image](https://private-user-images.githubusercontent.com/33731393/272883244-6f10f8c3-948c-4932-9e6f-a1ed71589ad9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMzgyMTcsIm5iZiI6MTcwMTAzNzkxNywicGF0aCI6Ii8zMzczMTM5My8yNzI4ODMyNDQtNmYxMGY4YzMtOTQ4Yy00OTMyLTllNmYtYTFlZDcxNTg5YWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDIyMzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZTRkZmJmNDQ5YTAzOWU3ZTgzZDFkMDQ0NDYwOWZhY2QwYTg2ZDNiZDU4MDljYmE5MmE4ZTE4NDNhNWJmOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PMf-OAecCDwvSuKZo_N8S880YLHTLFwdLH-mVCbCuHM) ![image](https://private-user-images.githubusercontent.com/33731393/272883798-3f6165a4-a4fc-4b38-be2d-9f815c43995e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMzgyMTcsIm5iZiI6MTcwMTAzNzkxNywicGF0aCI6Ii8zMzczMTM5My8yNzI4ODM3OTgtM2Y2MTY1YTQtYTRmYy00YjM4LWJlMmQtOWY4MTVjNDM5OTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDIyMzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTBhNWJlMDAzYTllZDJkNmU5Mzc3MzI0Y2U5NzU3MTE2YTIwY2I3NzRmNDY4M2YyY2JlOTk0OTVmNjRkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmX5kyGDm9GMLmZhgRTefsh-qirOep-axiC0a2_5av0)

Hey any updates on this? For some reason tomorrow.io is the only good weather api I can find and it works well with this card other then this one issue

**Comment by pkissling** [comment]
> > thanks for reporting the issue. problem is related to the fact that although Tomorrow.io supports `weather.get_forecast` they still supply the deprecated `forecast` attribute. clock-weather-card is currently implemented in a way that it tries to read `forecasts` and only if this attribute does not exist, it subscribes to `weather.get_forecast`. i think i have to change the logic on how the card identifies whether the current entities supports `weather.get_forecast`. ![image](https://private-user-images.githubusercontent.com/33731393/272883244-6f10f8c3-948c-4932-9e6f-a1ed71589ad9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMzgyMTcsIm5iZiI6MTcwMTAzNzkxNywicGF0aCI6Ii8zMzczMTM5My8yNzI4ODMyNDQtNmYxMGY4YzMtOTQ4Yy00OTMyLTllNmYtYTFlZDcxNTg5YWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDIyMzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZTRkZmJmNDQ5YTAzOWU3ZTgzZDFkMDQ0NDYwOWZhY2QwYTg2ZDNiZDU4MDljYmE5MmE4ZTE4NDNhNWJmOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PMf-OAecCDwvSuKZo_N8S880YLHTLFwdLH-mVCbCuHM) ![image](https://private-user-images.githubusercontent.com/33731393/272883798-3f6165a4-a4fc-4b38-be2d-9f815c43995e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMzgyMTcsIm5iZiI6MTcwMTAzNzkxNywicGF0aCI6Ii8zMzczMTM5My8yNzI4ODM3OTgtM2Y2MTY1YTQtYTRmYy00YjM4LWJlMmQtOWY4MTVjNDM5OTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDIyMzE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkZTBhNWJlMDAzYTllZDJkNmU5Mzc3MzI0Y2U5NzU3MTE2YTIwY2I3NzRmNDY4M2YyY2JlOTk0OTVmNjRkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmX5kyGDm9GMLmZhgRTefsh-qirOep-axiC0a2_5av0)
> 
> Hey any updates on this? For some reason tomorrow.io is the only good weather api I can find and it works well with this card other then this one issue

hi @Rehold, i will try fixing it in the course of the next week

**Comment by Rehold** [comment]
I ❤️ u

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pkissling** [comment]
i just released https://github.com/pkissling/clock-weather-card/releases/tag/2.1.6 containing the fix
