### ISSUE TITLE
The card does not work

### ISSUE THREAD

**Issue by znack14** [pkissling/clock-weather-card#23]
Good day.  The card does not work.  OpenWeather weather operator, everything is written: 
type: custom:clock-weather-card
 entity: weather.irpin
 animated_icon: true
 forecast_days: 5
 locale: en
although it may or may not be necessary. Installation via Hacs

**Comment by pkissling** [comment]
thanks for reporting the issue. i have never tried the OpenWeather weather provider. i will have a look and see what i can do to make it work

**Comment by detroitgoose** [comment]
> i was not able to reproduce the problem.

I was. The card doesn't show up if you use "onecall_hourly"

Is that a bug or no? I would prefer to use the hourly service if possible.

Cheers and thank you!

**Comment by pkissling** [comment]
i can look into accepting `onecall_hourly`, but that might take some time. i would have to add some logic to aggregate all hours of each day and calculate the avg/max/min temp.

**Comment by pkissling** [comment]
> PirateWeather

hi @usernein, can you create a new issue for the pirateweather provider? i will look into it

**Comment by pkissling** [comment]
hi @usernein @znack14 @boulala @detroitgoose, i just implemented the hourly support in #41 
it will be released in the next couple of days with `1.0.5`

**Comment by detroitgoose** [comment]
@pkissling Apologies for late reply. Everything I've tested works as expect. Very nice, thank you!
