### ISSUE TITLE
Language stuck in English - "locale" option does not work

### ISSUE THREAD

**Issue by DjavierHG** [pkissling/clock-weather-card#24]
I have HA language and location in Spanish but card shows the data in English. I have set  locale card property to "es" to try to force the change but card still displays weather text in english.

**Comment by joostvkempen** [comment]
Confirmed for 'NL', also several restarts of HA and reloading browser did not change language shown

**Comment by LeonB87** [comment]
pkissling mentioned in PR #17 that some additional work needs to be done that he will look at.

**Comment by pkissling** [comment]
hi @DjavierHG, there is no such translation available for spanish. could you contribute the corresponding translations?
https://github.com/pkissling/clock-weather-card/tree/master/src/localize/languages

**Comment by pkissling** [comment]
hi @joostvkempen, NL language was added with release 1.0.3 from yesterday evening. can you check whether you run the latest version? 
for me, the card properly shows Dutch translations
![image](https://user-images.githubusercontent.com/33731393/196431012-f14c3bd3-6866-4c4a-89e9-2da11aaf0a44.png)

**Comment by joostvkempen** [comment]
Hmm, that's strange! I'm definitely on 1.0.3 and tried several things. After updating I've added 'locale', restarted HA and refreshed frontend (incl. deleting cookies etc.), but nothing changed. In the documentation it states: "If not provided, falls back to the locale set in HA". My locale is set to NL, so I tried removing 'locale' from the card, also without success.

I'll wait some more, sometimes patience is golden ;-)

**Comment by DjavierHG** [comment]
> hi @DjavierHG, there is no such translation available for spanish. could you contribute the corresponding translations? https://github.com/pkissling/clock-weather-card/tree/master/src/localize/languages

Done!

**Comment by LeonB87** [comment]
I have it the other way around, I'm now stuck at the NL language. When I switch to en, only the datetime format changes. Tried clearing my cache as well.

![msedge_IYga89iF4b](https://user-images.githubusercontent.com/10503724/196462210-569b2118-f3ef-4f8e-8adf-0c48758a54fb.gif)

**Comment by pkissling** [comment]
hi @LeonB87,
i realised that there were multiple sources of truth with regards to the locale.
I fixed it via https://github.com/pkissling/clock-weather-card/pull/27. Once a new version is released, the config parameter `locale` with take precedence. if not available, it will fallback to the locale set in HA.

**Comment by alexandrechoske** [comment]
hi @pkissling I am also trying to change to "pt-BR" but with no success, only keep the EN version ;)

**Comment by pkissling** [comment]
> hi @pkissling I am also trying to change to "pt-BR" but with no success, only keep the EN version ;)
hi @alexandrechoske there was an issue with the mapping of `pt-BR` file. will be fixed with the next release as well

**Comment by nightfever77** [comment]
Same issue with German. HA localization is set to German. Card is falling back to English no matter if I set locale: de or not

**Comment by pkissling** [comment]
i just released 1.0.4. hope this solves all discussed issues. otherwise, please feel free to open a new issue. thanks for your feedback guys - appreciated.

and @DjavierHG, can you create a pull request for the `es.json` translations? let me know if you need help with that

**Comment by nightfever77** [comment]
Confirmed, thanks.

**Comment by Poncharello** [comment]
Hi @pkissling,
I've just added the Italian translation .json file.

Cheers!
