### ISSUE TITLE
User-configurable time format

### ISSUE THREAD

**Issue by cpinkham** [pkissling/clock-weather-card#240]
**Is your feature request related to a problem? Please describe.**
I would like to have the ability to display a 12-hour time format without the AM/PM indicators to save space.

**Describe the solution you'd like**
I am looking for your preference on how to implement so I can submit a pull request.  I can either allow generic strings like 'h:mm' in the current time_format field which would mean disabling the "must be '12' or '24'" sanity check in types.js or I can create a new optional time_format_str field which is a string type and doesn't have any sanity check in types.js.

**Describe alternatives you've considered**
I am currently running a patched version which enables this functionality using a new time_format_str field.

**Additional context**
Not much to show here:

time_format: h:mm

OR with a new field:

time_format_str: h:mm

**Comment by pkissling** [comment]
i think it makes sense to introduce `time_pattern` property similar to `date_pattern`

**Comment by cpinkham** [comment]
OK, thanks. I didn't even notice that date already supported something like this.  I'll take a look at it and see about generating a pull request for time.

**Comment by pkissling** [comment]
Released `2.1.0` including #242
