### ISSUE TITLE
Customizing elements

### ISSUE THREAD

**Issue by GGSSDD** [pkissling/clock-weather-card#241]
Hi,

i would like to customize some card elements, the temperature bar and pointer height in particular.
Is there a way to do this? Even if it means using css styles with card-mod. I tried that but I honestly don’t have a clue on how to structure the syntax, especially that i can’t view the source for this card.

Thank you.

**Comment by pkissling** [comment]
hi, an example of using card-mod can be found here:
https://github.com/pkissling/clock-weather-card/issues/99#issuecomment-1297289467
the sources of the card (to find the corresponding element names) can be found here: https://github.com/pkissling/clock-weather-card/blob/master/src/clock-weather-card.ts#L289

**Comment by enriquerollon** [comment]
Hi, 
Please, could you share your code? I also would like to customize the height of the temperature bar and pointer, but I can't get it.... 

Thank you very much, and thank you for this great card :)

**Comment by GGSSDD** [comment]
Hi,

I hope this helps you.

```
type: custom:clock-weather-card
card_mod:
  style: |
    forecast-temperature-bar {
      height: 8px !important;
    }
    forecast-temperature-bar-current-indicator-dot {
      width: 8px !important;
    }
    clock-weather-card-today-right-wrap-top {
      text-align: right !important;
      font-size: 15px !important;
    }
    clock-weather-card-today-right-wrap-bottom {
      justify-content: left !important;
      font-size: 11px !important;
    }
```

**Comment by enriquerollon** [comment]
It worked very well, thank you very much
