### ISSUE TITLE
Card does not show correct Temperature format

### ISSUE THREAD

**Issue by sauln1** [pkissling/clock-weather-card#255]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
2.0.1
**Last working release (if known):**
Unknown
**Browser and Operating System:**
Edge, Opera, Chrome, Safari

All browsers are up to date, no other aspects of home assistant are having issues.

**Description of problem:**

The Card at a glance does not reflect the correct temperature format. When clicking on the card for more details, the correct format is shown, however when viewing the card from the dashboard only C is shown. The correct temperature format is also shown in other cards. Changing the card's Temperature Format in UI does not have any effect. I've also tried creating a template and doing the conversion math myself to no effect. After each change attempt, I've restarted HA and reloaded the YAML.

![image](https://github.com/pkissling/clock-weather-card/assets/29236642/aa95452e-64e2-46d0-a5ee-a62ee0dae949)
![image](https://github.com/pkissling/clock-weather-card/assets/29236642/b0b14e3f-82c5-4b21-b910-bc62d1b22eec)
![image](https://github.com/pkissling/clock-weather-card/assets/29236642/45736749-8e57-4204-a2ad-49d8d5faafb2)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by pkissling** [comment]
the card uses the unit system [defined in HA](https://www.home-assistant.io/docs/configuration/basic/). if you want to override the unit system defined in HA, please upvote https://github.com/pkissling/clock-weather-card/issues/144
