### ISSUE TITLE
Option for the clock to show seconds?

### ISSUE THREAD

**Issue by jarrah31** [pkissling/clock-weather-card#258]
**Describe the solution you'd like**
I'm now using your lovely clock weather card on my hallway dashboard tablet having previously use two separate cards to do the same job. However my daughter has one problem in that the clock doesn't show seconds. :) 

I was previously using `custom:simple-clock-card` which gave me the option to display seconds, and my daughter relied on that when waiting for a specific time to leave the house for school (she doesn't like to be late...).

I'd rather not go back to having separate clock and weather cards as that would mean not using yours, so hopefully this is something you may be able to consider please.

**Comment by pkissling** [comment]
hi there, glad you like the card. this indeed is a bug i have to fix. yes, please create a new issue

**Comment by jarrah31** [comment]
Thanks, new issue opened: https://github.com/pkissling/clock-weather-card/issues/259
