### ISSUE TITLE
something wrong in the display of the card

### ISSUE THREAD

**Issue by heinemannj** [pkissling/clock-weather-card#263]
Using the actual version provide by HASC

There is something wrong in the display of the card:

![image](https://github.com/pkissling/clock-weather-card/assets/3251642/9b958364-9c6f-48cb-a64a-212cc60e224c)

```
type: custom:clock-weather-card
entity: weather.raesfeld_ka
title: ""
sun_entity: sun.sun
weather_icon_type: line
animated_icon: true
forecast_days: 5
locale: de
time_format: 24
date_pattern: P
hide_today_section: false
hide_forecast_section: true
hide_clock: false
hide_date: false
```

**Comment by pkissling** [comment]
`P` is not a valid luxon token: https://github.com/moment/luxon/blob/master/docs/formatting.md#table-of-tokens
