### ISSUE TITLE
Can't get days visible

### ISSUE THREAD

**Issue by dennidoubles** [pkissling/clock-weather-card#291]
Hi there,
I'm not sure where to put this, but I have difficulties configuring the card with the days of the forecast visible:

![image](https://github.com/pkissling/clock-weather-card/assets/71798417/7563b328-02f6-47f1-9bb0-9ae4f5882f4b)

What am I missing? Is this a bug, or do I need to change something? Please help.

**Comment by pkissling** [comment]
i think this has to do with your weather provider delivering the forecast date in a non ISO-format. which weather provider are you using?

> Hi there, I'm not sure where to put this, but I have difficulties configuring the card with the days of the forecast visible:
> 
> ![image](https://private-user-images.githubusercontent.com/71798417/287295790-7563b328-02f6-47f1-9bb0-9ae4f5882f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2Nzg3NTEsIm5iZiI6MTcwMTY3ODQ1MSwicGF0aCI6Ii83MTc5ODQxNy8yODcyOTU3OTAtNzU2M2IzMjgtMDJmNi00N2YxLTliYjAtOWFlNGY1ODgyZjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA4MjczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMDc1ZTFlMzI4MTM0M2I2MGM5ZTBkMjRiMTVmMjk3YTQ5NzYzZTdjYjYxMDk2ODg2NmI2Y2NlOGE3NTM0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZyFzWuZxvq7qYOfUr1TNqe6jtSCYufrgmQq0PpORhdo)
> 
> What am I missing? Is this a bug, or do I need to change something? Please help.

**Comment by exotsk** [comment]
Meteorologisk institutt (Met.no)
OpenWeatherMap
Yandex.Weather

**Comment by exotsk** [comment]
![image](https://github.com/pkissling/clock-weather-card/assets/54969124/2d91b33d-1272-4725-908a-450733ea3fd4)
![image](https://github.com/pkissling/clock-weather-card/assets/54969124/29978496-f612-4d5b-84cd-753aa5a576ef)
![image](https://github.com/pkissling/clock-weather-card/assets/54969124/f03ce729-736b-41cb-be8b-7fa0f0e6be53)
i am try back 1-2 version and master. but no result

**Comment by pkissling** [comment]
closing due to lack of response
