### ISSUE TITLE
The forecast_rows block randomly disappears

### ISSUE THREAD

**Issue by rbalaev** [pkissling/clock-weather-card#295]
The block with the weather forecast disappears, and during the day it appears and then disappears.
<img width="561" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/90223039/06efa47f-e78f-4609-937a-b26692a3323c">
<img width="563" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/90223039/4ffdef36-d54d-45c1-ba8e-f349e21824f1">

**Comment by pkissling** [comment]
can you please provide me your lat, long and altitude configured for the met.no weather provider? i would like to reproduce the problem, if possible

**Comment by Kibakus** [comment]
> Можете ли вы предоставить мне свою широту, долготу и высоту, настроенные для провайдера погоды met.no? я хотел бы воспроизвести проблему, если это возможно
my example (Yekaterinburg)
56.8383,60.6035

**Comment by pkissling** [comment]
quick heads up: i am trying to reproduce with met.no in yekaterinenburg. so far i was not able to reproduce the issue.

**Comment by Kibakus** [comment]
> quick heads up: i am trying to reproduce with met.no in yekaterinenburg. so far i was not able to reproduce the issue.

I can send it only in a week logs :(

Please write to me in telegram @Kibakus

The error is exactly like in the screenshot

**Comment by wu5** [comment]
The same problem - block with weekly or hourly forecast is not displayed. There are many errors in the console. 

![ksnip_20231213-194832](https://github.com/pkissling/clock-weather-card/assets/12344392/48d7bf03-69b0-4ab4-a005-c3b957bed147)

I checked Met.no and OpenWeatherMap providers - the same does not work. What is characteristic, I am also from Russia (52.4870, 85.1466).

Finally, I tried specifying Berlin coordinates and the forecast block showed up and the errors disappeared. I hope this will give you an idea where to look for the problem.

**Comment by pkissling** [comment]
> The same problem - block with weekly or hourly forecast is not displayed. There are many errors in the console.
> 
> ![ksnip_20231213-194832](https://private-user-images.githubusercontent.com/12344392/290194763-48d7bf03-69b0-4ab4-a005-c3b957bed147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzgyNDUsIm5iZiI6MTcwMjQ3Nzk0NSwicGF0aCI6Ii8xMjM0NDM5Mi8yOTAxOTQ3NjMtNDhkN2JmMDMtNjliMC00YWI0LWEwMDUtYzNiOTU3YmVkMTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE0MzIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNTZiMGI5OGFmMThlNGZmNGJkYjVmYzkzZmExM2JlMGY1NWFkZDZhOTM4MThiZTkxN2VhZGM3NjVhZjJjMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jY1pWc6nLdveiMLGNR3jIeo_xR6L9HFQB6O3trVB2XA)
> 
> I checked Met.no and OpenWeatherMap providers - the same does not work. What is characteristic, I am also from Russia (52.4870, 85.1466).
> 
> Finally, I tried specifying Berlin coordinates and the forecast block showed up and the errors disappeared. I hope this will give you an idea where to look for the problem.

thank you. with the coordinates you provided i am able to reproduce the problem. i will try to create a fix tomorrow

**Comment by pkissling** [comment]
released 2.1.10, which should fix the issue. it had to do extremely low temperatures and the fact that no dedicated color was provided fur such extreme ranges.
i also added a darker blue color for temperatures below -20 degrees
<img width="453" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/33731393/a3253ede-e9d8-4b39-8749-8e316a8fd501">

**Comment by Kibakus** [comment]
> released 2.1.10, which should fix the issue. it had to do extremely low temperatures and the fact that no dedicated color was provided fur such extreme ranges. i also added a darker blue color for temperatures below -20 degrees <img alt="image" width="453" src="https://private-user-images.githubusercontent.com/33731393/290316030-a3253ede-e9d8-4b39-8749-8e316a8fd501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0OTg4NjMsIm5iZiI6MTcwMjQ5ODU2MywicGF0aCI6Ii8zMzczMTM5My8yOTAzMTYwMzAtYTMyNTNlZGUtZTlkOC00YjM5LTg3NDktOGUzMTZhOGZkNTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIwMTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NDY1YmZlMWRhYjhlMjllNDdiM2MwNWQyYzA3ZjhkODI0ZjMxNTU0YWY1NGJhYTgyMWQ0ZTQzYjE0M2RmZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5e2wpW6t635GHOwcFPzgFb-2hAQ6QkmDGJUpsFZI6fk">

Thank you, but we sometimes have -30, as well as -40)))

**Comment by pkissling** [comment]
poor you :D 
temperatures -20 degrees will still be rendered correctly. the color blue color will just not go darker below -20 degrees. but the card should render the bars properly

**Comment by Kibakus** [comment]
> poor you :D temperatures -20 degrees will still be rendered correctly. the color blue color will just not go darker below -20 degrees. but the card should render the bars properly

It’s sad that for us -20 is no different from -40 :)

**Comment by Kibakus** [comment]
> > poor you :D temperatures -20 degrees will still be rendered correctly. the color blue color will just not go darker below -20 degrees. but the card should render the bars properly
> 
> It’s sad that for us -20 is no different from -40 :)

It’s funny that less than -20 degrees was not envisaged.
