### ISSUE TITLE
Updated to new HA update and can’t load my ui now

### ISSUE THREAD

**Issue by Rehold** [pkissling/clock-weather-card#296]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser
- [ ] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:** Latest 

**Last working release (if known):** last I think 

**Browser and Operating System:** latest and mobile app and fully kisok

**Description of problem:** Ever since I updated to the newest HA version It works for about a hour then tells me to reload the ui, I disabled my weather intergration so it won’t display anything and this stopped happening, so I’m assuming it’s a issue with this card

Got these errors on my display and phone mobile app

https://dpaste.org/Q3ZfG

Just the normal ha error saying reload ui

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
It’s 12am and I’m on mobile sorry if this explanation sucks I’ve been trying to debug it for a hour

**Comment by Rehold** [comment]
Sorry if I’m wrong I really can’t figure out what else it would be tho, and since I’ve disabled it it’s been working so

**Comment by panteLx** [comment]
Duplicate - Check issue #276

**Comment by pkissling** [comment]
closing for #276 
i will install FullyKiosk on my tablet today to see if i can reproduce the problem
