### ISSUE TITLE
Invalid DateTime 

### ISSUE THREAD

**Issue by matomatusov** [pkissling/clock-weather-card#306]
Hi,
I don't know why the days are not shown in the weather forecast.
Don't know what the problem could be?

![image](https://github.com/pkissling/clock-weather-card/assets/129114957/f92d0de7-68e5-4798-a573-47840245dd46)

Thanks :)

**Comment by pkissling** [comment]
hi @matomatusov, which weather provider are you using?

**Comment by matomatusov** [comment]
Hi @pkissling,
I use the provider weather wunderground.

**Comment by pkissling** [comment]
i am not able to reproduce the problem, as i understand that i need a weather wunderground station to integrate the weather forecast in my HA instance. 

however, i have the feeling that the date format in weather underground's forecast entities does not comply to ISO 8601. can you please provide the date format reported by weather wunderground?
<img width="898" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/33731393/6f1c5bcc-b18e-43d0-9467-4ab9e1677421">

**Comment by matomatusov** [comment]
Hi,
I'm sending the format of the local time of observation.

![WUnderground weather Time](https://github.com/pkissling/clock-weather-card/assets/129114957/86fd06ff-85c6-4909-bdf4-fd46013cbac5)

**Comment by matomatusov** [comment]
Hi,
thank you for the great work.
