### ISSUE TITLE
Time in the bar is not aligned with HA time system

### ISSUE THREAD

**Issue by killkenny** [pkissling/clock-weather-card#315]
**Checklist:**

- [X] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
2.2.1

**Last working release (if known):**

**Browser and Operating System:**
HA on Pi4
Core
2024.1.0
Supervisor
2023.12.0
Operating System
11.3
Frontend
20240103.3

Issue identified from Chrome and from HA App
**Description of problem:**
The point that indicates the time in the daily bar is not aligned with the real-time. In the screenshot below, the time in the card is at the end of today's line (night) but the current time is almost 1 PM, so I expect to see the point in the middle of today's bar.
Here the screenshot of my card with the configuration used:
![image](https://github.com/pkissling/clock-weather-card/assets/70591805/f05d99b5-b1eb-47c8-95d0-3fa04e0da0dc)

Thank you

I expect to see the dot time aligned with the real-time (time in HA), so according to my screenshot, the dot should be in the 'middle' of the bar.
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Help to support with more details. Thank you

**Comment by pkissling** [comment]
hi @killkenny, did you - by any chance - find time to read the FAQ before creating this issue?

**Comment by killkenny** [comment]
Ops...my fault. I see that the issues is related with the provider I have included.
Thank you @pkissling  and I apologize.
