### ISSUE TITLE
Termperature nearby weather image

### ISSUE THREAD

**Issue by kroon040** [pkissling/clock-weather-card#317]
Hi,

Is it possible to have the option to have the temperature with the weather image, like this.

![Screenshot from 2024-01-06 07-51-57](https://github.com/pkissling/clock-weather-card/assets/40452265/3f1c9458-c2be-487c-93e2-f84c0f8c3b63)

**Comment by pkissling** [comment]
hi @kroon040, i'm afraid that's not possible. however you could use [`card-mod`](https://github.com/thomasloven/lovelace-card-mod) to achieve this result somehow
