### ISSUE TITLE
Get all CSS style elemts

### ISSUE THREAD

**Issue by Phoenix-DH** [pkissling/clock-weather-card#318]
Does anybody got a list of the stylable elements with card mod?
I am trying to make the icon and the temperature smaller to have a better view an a tablet.

I am nopt really familiar with that.

Thanks.

**Comment by adrianrdzv** [comment]
I'm using card-mod to align better the header texts and scales because I think by default the orientations are odd. Maybe this helps you:
```
    ha-card {
      font-size: 1rem;
    }
    clock-weather-card-today-left  {
      width: 25% !important;
    }
    clock-weather-card-today-right  {
      display: block !important;
      width: 75% !important;
    }
    clock-weather-card-today-right-wrap-top  {
      font-size: 1.2rem !important;
    }
    clock-weather-card-today-right-wrap-center  {
      font-size: 2.7rem !important;
    }
    clock-weather-card-today-right-wrap-bottom  {
      text-align: center !important;
      display: block !important;
    }
```

**Comment by Phoenix-DH** [comment]
@adrianrdzv Thank you for the initial starting point. My goal is to make the current temperature a little bit smaller and the main icon too. But here I only get it managed to change the size of all icons. I am not that familiar with styling 🤷🏼‍♂️

I will try and let you know.

**Comment by sparment** [comment]
@Phoenix-DH  I'm interested in this as well... Looking to do a bit of the opposite though and make the current temperature font larger. I'll let you know if I figure anything out. Please do the same!

**Comment by Phoenix-DH** [comment]
@sparment Sure, will do when I got the time to.

**Comment by sparment** [comment]
Actually, the post from @adrianrdzv had what I needed. Top is the current weather, center is the time, and bottom is the date.

          clock-weather-card-today-right-wrap-top  {
            font-size: 22px !important;
            text-align: left !important;
          }
          clock-weather-card-today-right-wrap-center  {
            font-size: 50px !important;
            text-align: left !important;
          }
          clock-weather-card-today-right-wrap-bottom  {
            text-align: left !important;
            font-size: 22px !important;
          }

**Comment by Phoenix-DH** [comment]
@sparment 

Great, thanks! This really helps, I got it. Just trying to remove some more space in between to get it more suitable for smaller displays.

**Comment by kroon040** [comment]
Nice to have the option to modify this.

Any Idea how I can acomplish that it de tekst is somehow like this. Temperature only  near the weather icon and time and date on the right

![Screenshot from 2024-01-06 07-51-57](https://github.com/pkissling/clock-weather-card/assets/40452265/dd2930ec-8b08-471d-ad92-f12d2aabed9b)

**Comment by Camatobe** [comment]
I also altered the stylings for my dashboard darkmode:
If you are interested I can share the card_mod styles as well
![image](https://github.com/pkissling/clock-weather-card/assets/51515686/c197153e-4326-4bb4-8a16-7a499a064525)

`card_mod:
  style: >
    ha-card {
      background: none;
      border: none;
    } 
    clock-weather-card-today-right-wrap-center {
      font-size: 6.5rem !important;
      font-weight: 700;
      opacity: 0.3;
      height: 5rem !important;
    }

    clock-weather-card-today-right-wrap-top,
    clock-weather-card-today-right-wrap-bottom {
      font-size: 1.5rem;
      font-weight: 500;
    } 

    clock-weather-card-today-right-wrap-top { 
     width: 100%; 
     text-align: end;
     display: block !important; 
    } clock-weather-card-today-left {
      max-height: 130px;
    } `

**Comment by RkcCorian** [comment]
> I also altered the stylings for my dashboard darkmode: If you are interested I can share the card_mod styles as well ![image](https://private-user-images.githubusercontent.com/51515686/299767827-c197153e-4326-4bb4-8a16-7a499a064525.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Njg3NDIsIm5iZiI6MTcwNjQ2ODQ0MiwicGF0aCI6Ii81MTUxNTY4Ni8yOTk3Njc4MjctYzE5NzE1M2UtNDMyNi00YmI0LThhMTYtN2E0OTlhMDY0NTI1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxOTAwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjlkMmYwNTNhM2IyMGZlZTExOTJlMzllZmY0ZWQ1ZTc5NDc4ZTg2ZGEwNmI1ZTgwM2FiMzgxMzQzODA5ZTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gqgk0ky6B-KhHtYgnHAst8bz1MGnoIkC_IMYDdvgLsU)
> 
> `card_mod: style: > ha-card { background: none; border: none; } clock-weather-card-today-right-wrap-center { font-size: 6.5rem !important; font-weight: 700; opacity: 0.3; height: 5rem !important; }
> 
> ```
> clock-weather-card-today-right-wrap-top,
> clock-weather-card-today-right-wrap-bottom {
>   font-size: 1.5rem;
>   font-weight: 500;
> } 
> 
> clock-weather-card-today-right-wrap-top { 
>  width: 100%; 
>  text-align: end;
>  display: block !important; 
> } clock-weather-card-today-left {
>   max-height: 130px;
> } `
> ```

May I ask how you created the hourly forecast as well? Many thanks!

**Comment by Camatobe** [comment]
Sure, it's https://github.com/decompil3d/lovelace-hourly-weather
Just between the clock and daily.

**Comment by RkcCorian** [comment]
> Sure, it's https://github.com/decompil3d/lovelace-hourly-weather Just between the clock and daily.

Cool! As I'm new to HA... how can I reach "Just between"? Do you have the full YAML of your card?

**Comment by Phoenix-DH** [comment]
Can imagine that he just added the component twice. First one only current. Then hourly, then second time only forecast.

**Comment by Camatobe** [comment]
Sure,
Easy way: 
- vertical stack
- clock weather card, hide the forecast (see documentation for that)
- hourly weather card
- clock weather card, only show the forecast (see documentation for that)
- use card mod to remove all card backgrounds (set them to transparent) (see card mod addon documentation)

This way you have 3 weather cards stacked.

My way:
(My slow walk tablet could not handle the amount of weather requests for 3 cards)
 I used card mod and some css magic to make space between clock and forecast.
After that I moved the hourly card in that exact spot:
- vertical stack 2 cards
- hourly -> position absolut, height 0px, transform: translateY to the right height.

**Comment by RkcCorian** [comment]
> Sure, Easy way:
> 
> * vertical stack
> * clock weather card, hide the forecast (see documentation for that)
> * hourly weather card
> * clock weather card, only show the forecast (see documentation for that)
> * use card mod to remove all card backgrounds (set them to transparent) (see card mod addon documentation)
> 
> This way you have 3 weather cards stacked.
> 
> My way: (My slow walk tablet could not handle the amount of weather requests for 3 cards) I used card mod and some css magic to make space between clock and forecast. After that I moved the hourly card in that exact spot:
> 
> * vertical stack 2 cards
> * hourly -> position absolut, height 0px, transform: translateY to the right height.

Would it be possible to share the YAML code? Many thanks!!!

**Comment by Camatobe** [comment]
> Would it be possible to share the YAML code? Many thanks!!!

Have fun with it. 
I have to deal with some nasty layout shift. I may alter the position of hourly to the bottom and move it up later

```
type: vertical-stack
cards:
  - type: custom:hourly-weather
    entity: weather.weather_entity
    name: ' '
    show_wind: 'false'
    show_precipitation_amounts: false
    show_precipitation_probability: true
    icons: true
    language: de
    colors:
      cloudy: '#444'
    label_spacing: '3'
    num_segments: '19'
    card_mod:
      style: |
        ha-card {
          background: none;
          border:none;
          height: 0;
          transform:translateY(160px);
          transition: none;
        }
  - type: custom:clock-weather-card
    entity: weather.weather_entity
    sun_entity: sun.sun
    weather_icon_type: fill
    animated_icon: true
    forecast_rows: 9
    date_pattern: ccc, DDD
    locale: de
    time_format: 24
    hide_today_section: false
    hide_forecast_section: false
    tap_action:
      action: navigate
      navigation_path: /lovelace-ipad/more_weather
    card_mod:
      style: >
        ha-card {
          background: none;
          border: none;
        } 
        forecast-temperature-bar-current-indicator-dot {
          width: 1.5rem;
        } 
        clock-weather-card-today {
          margin-bottom: 170px;
        }

        clock-weather-card-forecast {
          display: block !important;
        }

        clock-weather-card-today-right-wrap-center {
          font-size: 6.5rem !important;
          font-weight: 700;
          opacity: 0.3;
          height: 5rem !important;
        }

        clock-weather-card-today-right-wrap-top,
        clock-weather-card-today-right-wrap-bottom {
          font-size: 1.5rem;
          font-weight: 500;
        } 

        clock-weather-card-today-right-wrap-top { 
         width: 100%; 
         text-align: end;
         display: block !important; 
        } 
        clock-weather-card-today-left {
          max-height: 130px;
        }
```

**Comment by RkcCorian** [comment]
@Camatobe : Many thanks!! / Vielen Dank! :-)

**Comment by RkcCorian** [comment]
I tried a different approach but I'm cannot get it fully. Do you have an idea? My problems left
- Width of hourly is not correct
- Space after the whole card
```
type: custom:mod-card
card:
  type: vertical-stack
  title: Zeit & Wetter
  cards:
    - type: custom:clock-weather-card
      entity: weather.forecast_home
      sun_entity: sun.sun
      temperature_sensor: sensor.outdoor_temp
      weather_icon_type: line
      animated_icon: true
      forecast_rows: 5
      time_pattern: HH:mm:ss
      time_format: 24
      date_pattern: cccc, d.MM.yyyy
      hide_today_section: false
      hide_forecast_section: false
      hide_clock: false
      hide_date: false
      hourly_forecast: false
      use_browser_time: false
      time_zone: null
      card_mod:
        style: |
          clock-weather-card-today-right-wrap-center {
            opacity: 0.5;
            height: 5rem !important;
          }
          clock-weather-card-today-right-wrap-top,
          clock-weather-card-today-right-wrap-bottom {
            font-size: 1.5rem;
            font-weight: 500;
          }
          clock-weather-card-today-right-wrap-top { 
            width: 100%; 
            text-align: end;
            display: block !important; 
          } clock-weather-card-today-left {
            max-height: 130px;
          }
          forecast-temperature-bar-background {
            background: rgba(255, 255, 255, 0.2) !important;
          }
          clock-weather-card-today {
            margin-bottom: 105px;
          }
    - type: custom:hourly-weather
      entity: weather.forecast_home
      name: null
      icons: true
      show_date: 'false'
      show_wind: 'false'
      label_spacing: '2'
      offset: '0'
      num_segments: '12'
      show_precipitation_probability: false
      show_precipitation_amounts: false
      hide_temperatures: true
      card_mod:
        style: |
          ha-card {
            background: none !important;
            position: absolute;
            top: 220px;
            box-shadow: none;
            border:none;
          }

```
<img width="365" alt="image" src="https://github.com/pkissling/clock-weather-card/assets/79741077/8193a609-33c1-4cf9-8b84-c5e61799bd3b">

**Comment by maodun96** [comment]
> I also altered the stylings for my dashboard darkmode: If you are interested I can share the card_mod styles as well ![image](https://private-user-images.githubusercontent.com/51515686/299767827-c197153e-4326-4bb4-8a16-7a499a064525.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjkzODgsIm5iZiI6MTcxODk2OTA4OCwicGF0aCI6Ii81MTUxNTY4Ni8yOTk3Njc4MjctYzE5NzE1M2UtNDMyNi00YmI0LThhMTYtN2E0OTlhMDY0NTI1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxMTI0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGI3NDVjZDFlZWM2OTRlODM3NDg5NTkwZDliOTMxYWFmNGI3MjQwZDJkMTFjMWU1Mzk4MjMxODZlYjJhZTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Pf9CJ7M6p-TPblapHnLgoafgOpJx89D_g8UKk_YiTw)
> 
> `card_mod: style: > ha-card { background: none; border: none; } clock-weather-card-today-right-wrap-center { font-size: 6.5rem !important; font-weight: 700; opacity: 0.3; height: 5rem !important; }
> 
> ```
> clock-weather-card-today-right-wrap-top,
> clock-weather-card-today-right-wrap-bottom {
>   font-size: 1.5rem;
>   font-weight: 500;
> } 
> 
> clock-weather-card-today-right-wrap-top { 
>  width: 100%; 
>  text-align: end;
>  display: block !important; 
> } clock-weather-card-today-left {
>   max-height: 130px;
> } `
> ```

@Camatobe 
Hi, how did you change the bottom color? Did you change it through the theme?
![image](https://github.com/pkissling/clock-weather-card/assets/43996175/bbcb55d0-6608-492f-a0ad-8acaad2f35f1)
