### ISSUE TITLE
Show also today in forecast part.

### ISSUE THREAD

**Issue by Begie1605** [pkissling/clock-weather-card#319]
Hi,
currently you can show the today section and the forecast section.
In the forecast now, as i use buienradar as weather entity, i have the forecast for the next 5 days.

It would be nice to have the today weather also shown in the forecast part (as an option). This would also then take a lot less space instead of showing the today part.

**Comment by pkissling** [comment]
https://github.com/pkissling/clock-weather-card#why-dont-i-see-the-current-day-in-my-weather-forecast
