### ISSUE TITLE
Humidity not showing on (iOS) companion app

### ISSUE THREAD

**Issue by cpohli** [pkissling/clock-weather-card#340]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
2.3.0

**Browser and Operating System:**
latest iOS and companion app

**Description of problem:**
I configured the new humidity sensor and it's working just fine and showing up at my desktop above the big temperature (i have "hide_clock": true set)
On the companion app under iOS it looks just like the old card - no humidity shown here.
This goes for iPhone and iPad.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by pkissling** [comment]
hi, did you try resetting the frontend cache yet?

**Comment by cpohli** [comment]
> hi, did you try resetting the frontend cache yet?

Oh man, im soewhat dumb, soory.
I did restart the devices and the app, but did not think about that. Now everything works as expected.

Thank you for making this card and all the effort, that goes into it! (and ansering dumb bug reports ;-))
