### ISSUE TITLE
Humidity from attribute

### ISSUE THREAD

**Issue by SGXander** [pkissling/clock-weather-card#342]
**Is your feature request related to a problem? Please describe.**
Not particularly

**Describe the solution you'd like**
The humidity display I would love to use but my value (from tomorrow.io) comes from a attribute of the weather entity. Could you add the ability to define this as an attribute?

**Describe alternatives you've considered**
Will look to use a helper entity in the meantime

**Additional context**
N/A

**Comment by pkissling** [comment]
hi @SGXander, what attribute do you mean? is it the attribute named `humidity`?

**Comment by SGXander** [comment]
> hi @SGXander, what attribute do you mean? is it the attribute named `humidity`?

Yep, just weather.tomorrow_io_home has an attribute called humidity not a separate entity

**Comment by pkissling** [comment]
this is already the default behaviour if you omit `humidity_sensor`. i extended the description https://github.com/pkissling/clock-weather-card/commit/9932690b34a5ac03fe1dcfaa754fdd441abc8b08
