### ISSUE TITLE
Feature request: Ability to show temperature with 1 decimal place

### ISSUE THREAD

**Issue by oleg-d** [pkissling/clock-weather-card#355]
**Is your feature request related to a problem? Please describe.**
I would like to see the main temperature with 1 dp. I use the card to show just the temperature and no date/time, so the temperature value is big text and I would like to have it with 1 dp.

**Describe the solution you'd like**
To be able to show main temperature with 1 dp

**Additional context**
![image](https://github.com/pkissling/clock-weather-card/assets/25592559/e39e0982-0aa8-4382-889b-3c007658b7e1)

**Comment by pkissling** [comment]
duplicates #111
