### ISSUE TITLE
Use SVG for non-animated icons

### ISSUE THREAD

**Issue by amondit** [pkissling/clock-weather-card#364]
**Is your feature request related to a problem? Please describe.**
I'm using card-mod to resize the icon and text sizes of this cards, but when I use `animated: false` (to avoid the high-cpu-usage bug when using animated svgs), the icons do look blurry (due to the fact that png icons are then used and not properly resized).

**Describe the solution you'd like**
There are already icons in the svg-static folders, could we use those when animated is set to false? Or add another configuration flag (`force-svg`?) if for some compatibility reasons we want to keep having PNGs when not animated.

**Describe alternatives you've considered**
I'm using animated: true so that I have good resized looking icons on my dashboard, but this causes high cpu usages on my low power tablets (so heat and unnecessary power usage). I also tried to recompile the card to force-use the svg-static icon folders, it worked but then I loose automatic updates from hacs.

Thanks a lot for considering this request!

**Comment by amondit** [comment]
I created a PR for it, let me know what you think.

Thanks!

**Comment by pkissling** [comment]
hi @amondit. thank you for the PR. i am currently on vacation. i will have a look in 10 days.

**Comment by amondit** [comment]
No rush, enjoy your vacations! :)

**Comment by pkissling** [comment]
merged and release https://github.com/pkissling/clock-weather-card/pull/366
