### ISSUE TITLE
Cs and Sk translation feeling temperature  or apparent temperature

### ISSUE THREAD

**Issue by matomatusov** [pkissling/clock-weather-card#368]
Hi,
it is a translation of the feeling temperature into Cs and Sk "pocitová teplota".

**Comment by pkissling** [comment]
would you please raise a PR with the corresponding changes? https://github.com/pkissling/clock-weather-card/tree/master/src/localize/languages

**Comment by matomatusov** [comment]
Hi,
can you give me a procedure to fix it there? I have no experience with it.

Thanks
