### ISSUE TITLE
Forecast rows missing after update.

### ISSUE THREAD

**Issue by geekypenguin** [pkissling/clock-weather-card#370]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser
- [x ] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
2.5.0
**Last working release (if known):**
2.3.0
**Browser and Operating System:**
Chrome on Windows 10 and Chrome on Android mobile

**Description of problem:**

Since updating to 2.5.0 my card has lots the forecast rows. I updated directly from 2.3.0 so i dont know if the issue was also present in 2.4.0.
My weather forecast is provided by the WeatherUnderground API from my personal weather station.
My card configuration hasnt changed since it worked, and is as follows:

```
type: custom:clock-weather-card
entity: weather.isouth857
temperature_sensor: sensor.isouth857_temperature
weather_icon_type: line
animated_icon: true
forecast_rows: 5
locale: en-GB
time_pattern: HH:mm
time_format: 24
hide_today_section: false
hide_forecast_section: false
hide_clock: false
hide_date: false
hourly_forecast: false
use_browser_time: false
time_zone: GB
```

**Javascript errors shown in the web inspector (if applicable):**

There are no errors shown in the browser console relating to the card nor the WU API. There are no errors shown in the home assistant logs either for the card.
The only error relating to WU is
```
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:737
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: April 28, 2024 at 9:54:17 PM (1 occurrences)
Last logged: April 28, 2024 at 9:54:17 PM

Entity sensor.isouth857_solar_radiation (<class 'custom_components.wundergroundpws.sensor.WundergroundPWSSensor'>) is using native unit of measurement '' which is not a valid unit for the device class ('irradiance') it is using; expected one of ['W/m²', 'BTU/(h⋅ft²)']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/cytech/Home-Assistant-wundergroundpws/issues/
```

**Additional information:**

**Comment by pkissling** [comment]
hi @geekypenguin, is this issue still relevant?
if yes, can you provide an api key so that i can try to reproduce the problem? i don't have a weather station, which i can add to wunderground.

**Comment by geekypenguin** [comment]
Yep still present in 2.6.0

I'll send the Ali key etc via a DM

**Comment by pkissling** [comment]
hi @geekypenguin,

thanks. i tried to reproduce the problem, but for me the card shows just fine: 
![image](https://github.com/pkissling/clock-weather-card/assets/33731393/be6e4e8e-5404-4e70-bcea-814ddc0b7445)

**Comment by pkissling** [comment]
can you try to fetch a weather forcecast using the *services* section in the *developer options*?
can you obtain current weather information using the service?

```
service: weather.get_forecast
target:
  entity_id: weather.isouth857
data:
  type: daily
```

![image](https://github.com/pkissling/clock-weather-card/assets/33731393/fbcc0491-3a78-4351-90e9-41ca4a83e214)

**Comment by geekypenguin** [comment]
I get the following message: 
` Failed to call service weather.get_forecast. Entity weather.isouth857 does not support this service`

Which is why I guess it's not working, so seems it's an issue with Underground rather than you. It's just odd that it was working fine then stopped working after an update with no changes to wunderground.

**Comment by pkissling** [comment]
i agree. maybe check if there are updates available for the wundergrund HACS component
