### ISSUE TITLE
please add Ukrainian language support

### ISSUE THREAD

**Issue by lakshinskij** [pkissling/clock-weather-card#38]
I really like your work. I'm from Ukraine. Please add Ukrainian language support. Thanks in advance

**Comment by MarcelW85** [comment]
You can raise a PR with your ukrainian translation.

**Comment by MarcelW85** [comment]
> I really like your work. I'm from Ukraine. Please add Ukrainian language support. Thanks in advance

You can raise a PR with your ukrainian translation.

**Comment by pkissling** [comment]
hi @lakshinskij, glad you the card.
Ukrainian was already incorporated #31 and #36. and will hence be included in the next release `1.0.5`
