### ISSUE TITLE
Animated icon on forecast section ?

### ISSUE THREAD

**Issue by aigle1234** [pkissling/clock-weather-card#382]
Hi,

Is there a way to get `animated_icon` also working on forecast section weather ?
![image](https://github.com/pkissling/clock-weather-card/assets/48964174/c9f5a6be-ede9-4ea6-b11e-44ece253065f)

Regards,

**Comment by pkissling** [comment]
hi, when i implemented the card i realized that the animated icons require quiet a lot of CPU time, so the dashboard would become unresponsive quickly. 

hence only the big icon can be animated
