### ISSUE TITLE
Card doesn't display on Lenovo Smart Clock

### ISSUE THREAD

**Issue by teek541** [pkissling/clock-weather-card#392]
I'm unsure as to why it's only on this device, I've tried the HA Companion App, Fully Kiosk Browser, and the standard browser.  The card throws a "custom element doesn't exist: clock-weather-card" error.  This only happens on this device.  I even tried dev mode on my desktop setting the resolution to the same as the clock and couldn't reproduce this error.  I tried clearing browser data/cache as well.

**Comment by pkissling** [comment]
hi @teek541, this is related to #380 and, i'm afraid, nothing i can do to fix on my side. it has to do with a pretty outdated browser engine on the Lenovo Smart Clock side

**Comment by teek541** [comment]
Thanks, I didn't see that post.  Apparently it's the WebView that needs to be updated.  I'm trying to figure out if it can be done w/o needing to hack a USB connection together.  if I figure it out I'll post on here.

**Comment by pkissling** [comment]
> Thanks, I didn't see that post. Apparently it's the WebView that needs to be updated. I'm trying to figure out if it can be done w/o needing to hack a USB connection together. if I figure it out I'll post on here.

cool. please do let me know. i would like to add a bullet point in the FAQ section regarding Lenovo Smart Clock
