### ISSUE TITLE
12 Hour Time Format not working

### ISSUE THREAD

**Issue by JpsCrazy** [pkissling/clock-weather-card#393]
**Checklist:**

- [X] I updated to the latest version available - 2024.5.5 (not pre-release)
- [X] I cleared the cache of my browser
- [X] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
2.7.0

**Last working release (if known):**
Unknown

**Browser and Operating System:**
Chrome 125.0.6422.113
Firefox 124.0.2
Windows 11

**Description of problem:**
Time only displays in 24h even if time_format: 12 is set.
time_format: 12 is a valid option, but does not cause a change. (12 and 24 both result in the card working, while non-accepted values throw an error which is expected.)

**Javascript errors shown in the web inspector (if applicable):**

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "action-handler-clock-weather" has already been used with this registry
```

```
Failure writing uncaught error to system log: Error: Cannot parse given Error object
    at Object.parse (error-stack-parser.js:35:23)
    at stacktrace.js:106:62
    at new Promise (<anonymous>)
    at fromError (stacktrace.js:105:20)
    at t (log-message.ts:37:31)
    at logging-mixin.ts:45:33
```

**Additional information:**
n/a

**Comment by pkissling** [comment]
hi @JpsCrazy, 

can you please share your full `clock-weather-card` yaml configuration? i am not able to reproduce the issue you are having

**Comment by pkissling** [comment]
do you provide a custom time pattern?

**Comment by JpsCrazy** [comment]
Yes, my time_pattern includes HH which is a 24 hour format... Oops! 
Thank you for honing in immediately on the issue!
