### ISSUE TITLE
"apparent sensor" not respecting locale?

### ISSUE THREAD

**Issue by Jese44** [pkissling/clock-weather-card#400]
**Checklist:**

- [ X] I updated to the latest version available
- [ X] I cleared the cache of my browser
- [ X] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**

**Last working release (if known):**
NA
**Browser and Operating System:**
Brave, Win10

Tested on EDGE browser aswell.
brave version 1.67.116 chromium: 126.0.6478.71 official build 64-bit
**Description of problem:**
I set an apparent sensor to the card and first I thought that the problem was within the apparent sensor config --> i renamed it and restarted HA --> in another card (entity card) i had to re-configure the entity (due to name change since it re-named the entity aswell) i then changed the renamed entity to the clock weather card but it still shows the english description "Feels like" whereas above it there is description of current weather in finnish ("Puolipilvistä" --> Partly cloudy)

it should show "Lämpötila tuntuu kuin" or "Tuntuu kuin" instead of "Feels like"
Add option to rename the "Feels like" or make it to use locale since the card seems to have locale option that works in weather description.
Photos:
-Proof i have used the re-named entity which has the name in finnish in the clock card config
-Proof that it shows "Feels like"
-proof of the entity data name "Friendly name.
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
![image](https://github.com/pkissling/clock-weather-card/assets/45014337/b4de2d76-5195-411c-99b8-8a57880c6a77)
![image](https://github.com/pkissling/clock-weather-card/assets/45014337/28281134-9fc9-4b7f-bdc7-39459dd67507)
![image](https://github.com/pkissling/clock-weather-card/assets/45014337/6428619d-7abc-4e13-8fbe-8581ba9ebe20)

**Comment by Jese44** [comment]
Android companion app shows "feels like" aswell

**Comment by pkissling** [comment]
hi @Jese44, the "feels like" was not yet translated into finish. could you please add the corresponding translation and create a pull request for it? thank you

**Comment by pkissling** [comment]
closing due to lack of response
