### ISSUE TITLE
AQI doesn't appear on mobile

### ISSUE THREAD

**Issue by isewise** [pkissling/clock-weather-card#403]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**

AQI sensor, when enabled, doesn't appear on mobile/HA app

**Last working release (if known):**

AQI sensor was added in latest release, v2.8.0

**Browser and Operating System:**

Android HA App, latest version: 2024.6.3-full

**Description of problem:**

After enabling the AQI sensor for the card, it shows up on my desktop/laptop browser, not on my HA app. Screenshots attached. Same dashboard, AQI sensor does not appear on mobile.

Desktop:
![image](https://github.com/pkissling/clock-weather-card/assets/26588241/43f2d351-a951-458c-abce-bf18e2721c02)

Android HA app:
![Screenshot_20240620-233846](https://github.com/pkissling/clock-weather-card/assets/26588241/59277c50-bcb5-47b8-a774-73052fd7ae4b)

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

Restarted HA app multiple times and toggled setting back and forth to try and initiate update for HA app.

**Comment by pkissling** [comment]
hi @isewise, have you cleared the cache in your HA companion app already?

**Comment by isewise** [comment]
That did the trick. I've never had to do that for a card refresh but good to know. You can close this out.
