### ISSUE TITLE
Background removal

### ISSUE THREAD

**Issue by pawellygan** [pkissling/clock-weather-card#407]
Is there an option to remove the background? Using card on Picture element looks a bit broken
I'm happy to keep it as "no background"

see below:

<img width="419" alt="Screenshot 2024-06-28 at 08 42 48" src="https://github.com/pkissling/clock-weather-card/assets/45388740/1b80d2ea-2385-4405-8ee1-3ee102c56250">

solution: use background: false

**Comment by Dion-HA** [comment]
I would also like to see this option of no background added or even better, to allow other themes using the theme: option.

Thanks!

Dion
