### ISSUE TITLE
Make icon, current temp and current condition optional

### ISSUE THREAD

**Issue by rymiller11** [pkissling/clock-weather-card#411]
First of all, this is my favorite card since it solves several issues with Home Assistant with showing the current time and weather.  Thanks for the great work.  My request:

**Is your feature request related to a problem? Please describe.**
I would like to show a daily forecast followed by an hourly forecast. So, in setting up 2 cards there are some redundant items displayed.

**Describe the solution you'd like**
I would like to have the ability to suppress (make optional) the display of the weather icon, current temp and condition.

**Additional context**
See here for an example of what I'm trying to do:
![Screenshot 2024-07-05 111946](https://github.com/pkissling/clock-weather-card/assets/89878121/92c59991-82b4-400c-b6d0-c81610919544)

**Comment by jengel84** [comment]
May I add one more request related to this?

Would it be possible to have time AND Temperature displayed large? Or maybe separate values to set size / hide each?

@pkissling thanks for the great work. Your card has is admired by all our guests on our lobby displays.

**Comment by pkissling** [comment]
> First of all, this is my favorite card since it solves several issues with Home Assistant with showing the current time and weather. Thanks for the great work. My request:
> 
> **Is your feature request related to a problem? Please describe.** I would like to show a daily forecast followed by an hourly forecast. So, in setting up 2 cards there are some redundant items displayed.
> 
> **Describe the solution you'd like** I would like to have the ability to suppress (make optional) the display of the weather icon, current temp and condition.
> 
> **Additional context** See here for an example of what I'm trying to do: ![Screenshot 2024-07-05 111946](https://private-user-images.githubusercontent.com/89878121/346202952-92c59991-82b4-400c-b6d0-c81610919544.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjU4NjEsIm5iZiI6MTcyMjQyNTU2MSwicGF0aCI6Ii84OTg3ODEyMS8zNDYyMDI5NTItOTJjNTk5OTEtODJiNC00MDBjLWI2ZDAtYzgxNjEwOTE5NTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExMzI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzYxYzk4Y2FjZmJlMzdiYzAwYjMzNDdhMDczMjkzNGU5NmY3MDQ5ODVjZmZjZjYxM2MyZGIyODY2MWY1YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9CkLSzCnx1jUw30xrz2aEILGXFuRv_DWLlGGISFbvic)

hi @rymiller11,
sorry for the late reply. have you tried `hide_clock: false`?
this option is supposed to hide the "top part" of the card.
https://github.com/pkissling/clock-weather-card#full-configuration

**Comment by pkissling** [comment]
> May I add one more request related to this?
> 
> Would it be possible to have time AND Temperature displayed large? Or maybe separate values to set size / hide each?
> 
> @pkissling thanks for the great work. Your card is admired by all our guests on our lobby displays.

hi @jengel84, thanks for the props. it is not possible to display time and temperature in large.
feel free to open a feature request if you would like to have this feature implemented.
however, a quick disclaimer: due to my other ongoing projects i will most likely not find the time to implement it - though PRs are always welcome
