### ISSUE TITLE
Missing italian translation of "feels-like" text

### ISSUE THREAD

**Issue by alexlia** [pkissling/clock-weather-card#413]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser
- [X] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
v2.8.0
**Last working release (if known):**

**Browser and Operating System:**
Firefox 128 on Windows 10

**Description of problem:**
Using italian language, the text of "Feels-like" item is not translated

The text can be translated in "Percepita", I've already forked the repo and corrected the text.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by pkissling** [comment]
hi @alexlia, would you also create a pull request to merge your changes into this repo?

**Comment by alexlia** [comment]
Working in v2.8.1, I'closing the bug
