### ISSUE TITLE
Translation and other

### ISSUE THREAD

**Issue by systempal** [pkissling/clock-weather-card#440]
Hello everyone,

I’d like to propose a couple of features that I think could significantly enhance our user experience:

Weekday Translation: It would be incredibly useful to have an option to translate the names of the weekdays within the rows. This would make the platform more inclusive, especially for users who are more comfortable with languages other than English.

Hide Temperature Circle: Currently, there’s a circle indicating the current temperature on the interface. While this is helpful for some, others might prefer a cleaner look. Adding an option to hide this element would give users more flexibility to tailor their experience.

I believe these updates could greatly improve usability and overall satisfaction. I’m keen to hear your thoughts on this and whether these features could be considered in a future update.

Thanks for considering my suggestions!

Best regards,
Simone.

**Comment by pkissling** [comment]
hey systempal,

just to clarify your first point about the weekday translations: clock-weather-card does already come with language support out of the box. so if i set my HA user's language the english, i get the following Italian weekdays:
![Screenshot 2024-10-03 at 13 31 17](https://github.com/user-attachments/assets/22c3157b-f460-4c77-a940-176106c0fdc2)

Can you please clarify what you mean by "Weekday Translation"?

**Comment by pkissling** [comment]
closing due to lack of response
