### ISSUE TITLE
newbie: install problem

### ISSUE THREAD

**Issue by rbhun** [pkissling/clock-weather-card#442]
hi
I am trying to install this from HACS

1, downloaded from HACS
2, the instructions say to manually add the resource /hacsfiles/clock-weather-card/clock-weather-card.js. However, if I open my resources, I already have a /hacsfiles/clock-weather-card/clock-weather-card.js?hacstag=XXXXXXXX added to it. Seems like its automatic now? I had that with other cards before. Even so, I tried to add it manually, same output.
3, restarted HA
4, added a new custom manual card, and pasted:
  type: custom:clock-weather-card
  entity: weather.home
5, got error: Custom element doesn't exist: clock-weather-card.

I tried checking other ways, I am pretty sure the resource is there? I cannot figure out why the card doesnt found it.

Thank you for any help.

**Comment by milsie** [comment]
same issue for me, it appears the entity does not exist..

**Comment by dexter8203** [comment]
I still run v 1.1.0. I get this error on anything past that.  Tried recently without luck, rolled back to 1.1.0 and it's working.

**Comment by mashdup** [comment]
Hey all, I had this issue too. Managed to find the right one now. Hope they update the readme

`entity: weather.forecast_home`

**Comment by rbhun** [comment]
of FFS.
Yes that solved it. I wish they'd update such things in the readme

EDIT: strangely enough, this works on my laptop and on my phone, but on the old ipad I have built into the wall says weather.forecast_home doesnt exist. Really weird.

**Comment by pkissling** [comment]
hi there, sorry for the late response. does this clarifying comment make the configuration easier? https://github.com/pkissling/clock-weather-card/commit/cc50f05de6bf95114c46a723ea810a06f5c56a8f

**Comment by TylonHH** [comment]
> hi there, sorry for the late response. does this clarifying comment make the configuration easier? [168150d](https://github.com/pkissling/clock-weather-card/commit/168150d647c3bfa0b9d498a443ec3d23eadaad41)

I wonder why I don't see this hint within HA in the HACS
