### ISSUE TITLE
Feels like translation

### ISSUE THREAD

**Issue by Nashevil** [pkissling/clock-weather-card#446]
Good morning,

I have noticed that in the translations it says Feels Like instead of in its translated language, for example

Spanish Feels like is translated as "Sensación térmica"
Catalan Feels like is translated as "Sensació tèrmica"

You can see other translations here: https://en.wikipedia.org/wiki/Apparent_temperature

I attach a photograph of how the translation lines are displayed:
![2024-09-05 08_16_37-Window](https://github.com/user-attachments/assets/f75921c9-fdf3-487b-bdd8-9f5fbc437c91)

Kind regards

**Comment by mrand** [comment]
For anyone that comes across this issue and wants to contribute, it's pretty easy to edit the file here on github and submit a pull-request.  Give it a try!

For translations, the files are here:
https://github.com/pkissling/clock-weather-card/tree/master/src/localize/languages

**Comment by Nashevil** [comment]
> For anyone that comes across this issue and wants to contribute, it's pretty easy to edit the file here on github and submit a pull-request. Give it a try!
> 
> For translations, the files are here: https://github.com/pkissling/clock-weather-card/tree/master/src/localize/languages

Thanks a lot
