### ISSUE TITLE
No weather icon and also udefined instead on verbal weather description

### ISSUE THREAD

**Issue by fedd** [pkissling/clock-weather-card#454]
I want to place this beautiful card of my dashboard but I'm seeing no big icon and no weather description:

![image](https://github.com/user-attachments/assets/f3ed99e9-3a60-404f-b8bf-de75b71091c9)

Looks like it cant decode what the Openweathermap has sent it?

My config is like this:

```
type: custom:clock-weather-card
entity: weather.openweathermap
sun_entity: sun.sun
temperature_sensor: sensor.wb_ms_60_temperature
humidity_sensor: sensor.wb_ms_60_humidity
weather_icon_type: line
animated_icon: true
forecast_rows: 5
time_pattern: HH:mm
time_format: 24
date_pattern: ccc, d.MM.yy
hide_today_section: false
hide_forecast_section: false
show_humidity: true
hide_clock: false
hide_date: false
hourly_forecast: false
use_browser_time: false
time_zone: Europe/Moscow
show_decimal: false
```

Openweathermap seems to return this:

![image](https://github.com/user-attachments/assets/0df9d145-6d88-4d39-b556-81908ff027a1)

And it is configured like this - note the non-English locale. I've tried to play with this setting switching to English but nothing of the above had changed:

![image](https://github.com/user-attachments/assets/89e4fcaf-6fa3-4f6c-9783-b62ace9198a1)

Any ideas?

**Comment by pkissling** [comment]
hi @fedd, there must be something wrong with your openweather integration / configuration. the state of the entity should not be `unknown` - since this is not a valid weather state

**Comment by fedd** [comment]
Thanks, switched to Meteorologisk institutt, works like a charm
