### ISSUE TITLE
Does it work with new 'Sections' dashboard?

### ISSUE THREAD

**Issue by robs23** [pkissling/clock-weather-card#456]
Does this card work with 'Sections'? I don't get it displayed  when picking new card and I'm getting 'Custom element not found' when trying to add it manually

**Comment by mfcltd** [comment]
No it doesn't look like it, I see this problem too.

**Comment by mrmireaux** [comment]
Works pretty well on the new sections in the dashboard. Use the card in different variations.

<img width="1059" alt="Bildschirmfoto 2024-09-30 um 13 08 19" src="https://github.com/user-attachments/assets/2f5d58f8-4d5c-433d-a011-fdcff79a28f8">

**Comment by molnarti** [comment]
how can i change the width of the of the tile on the "Sections" dashboard? so its taking a "double unit" width? 
![image](https://github.com/user-attachments/assets/f3bfc89e-412a-49ca-9b45-930139cf70ab)
