### ISSUE TITLE
Snow Icon Broken

### ISSUE THREAD

**Issue by BennyDaBee** [pkissling/clock-weather-card#46]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
1.0.5
**Last working release (if known):**
N/A
**Browser and Operating System:**
Chrome on Windows 11 - HA Running on HAOS

**Description of problem:**
The snow icon on the forecast is broken/non-exsistent. Top picture is of the custom card, and the bottom is when clicking to view more details. 
![image](https://user-images.githubusercontent.com/97147515/196995455-3070ff46-dcf6-4a8a-baed-30f0b8142446.png)
![image](https://user-images.githubusercontent.com/97147515/196996013-79d0d46a-d8ac-4145-8d86-4c0f78071cf8.png)

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**

**Comment by pkissling** [comment]
hi @BennyDaBee, thanks for reporting the issue.
can you provide the state of your weather entity (from the developer tools section in HA). i would like to know the `condition` attribute of the `weather.attributes.forecast` item

**Comment by BennyDaBee** [comment]
Hello @pkissling,

The state is below 

```- datetime: '2022-10-20'
  condition: snowy
  wind_bearing: 278
  temperature: 50
  templow: 35
  wind_speed: 6.21
  precipitation: 0```

**Comment by pkissling** [comment]
thanks. apparently the icons `snowy` and `snowy-rainy` did never work. there was a typo in the mapping (`snow` vs `snowy` and `snowy-rainy` vs `snowy-rain`
