### ISSUE TITLE
Adjustable font

### ISSUE THREAD

**Issue by therealkeng** [pkissling/clock-weather-card#463]
**Is your feature request related to a problem? Please describe.**
I have a tablet display and, unless I'm close enough to the tablet, it is a bit hard to see. 

**Describe the solution you'd like**
An option to increase (or reduce) the font size for the various elements.

**Describe alternatives you've considered**
N/A

**Additional context**
This project is actually much better than the simple clock I was using that didn't have the ability to change to AM/PM format. Thanks for this card.

**Comment by pkissling** [comment]
duplicates #362
