### ISSUE TITLE
Strange forecast temperatures when entity is not available

### ISSUE THREAD

**Issue by t2029** [pkissling/clock-weather-card#465]
Strange forecast temperatures when weather entity is not available. 

![11](https://github.com/user-attachments/assets/6b519fba-fbde-44ad-aae0-7e467157392d)
![12](https://github.com/user-attachments/assets/99fcbe06-48ce-4e9b-83ec-facfc75301f8)

**Comment by pkissling** [comment]
`unavailable` is not a supported weather state

**Comment by t2029** [comment]
But the forecast  shows other values ​​that are not used as expected!
