### ISSUE TITLE
Color Coding for AQI

### ISSUE THREAD

**Issue by inguy24** [pkissling/clock-weather-card#467]
**Is your feature request related to a problem? Please describe.**

The AQI always shows up as green in the card, but there is an established color code for the AQI based upon its combined severity. 

**Describe the solution you'd like**

Is it possible to change the highlighting to reflect the severity of the AQI based upon established color code standards? 

**Describe alternatives you've considered**

Changing the highlight color to reflect the AQI severity based upon established color code standards. Potentially need to add option to select US or European standards as color codes are different. 

**Additional context**
AQI color standards:
US: https://www.airnow.gov/aqi/aqi-basics/
European: https://airindex.eea.europa.eu/AQI/index.html {click on legend explained for chart)

**Comment by pkissling** [comment]
hi @inguy24, 
what i understand in your ticket is that the AQI badge does not update its color, is this correct?
Or is your request about updating clock-weather-cards AQI color codes to match the value of the official AQI scale?

**Comment by pkissling** [comment]
closing due to lack of response

**Comment by lazarevski** [comment]
Sorry for reopening this. For me, the color coding is working just fine, i.e. the badge color is changing depending of the AQI value. 

However, i'm guessing that the color codes are base on the US scale? I'm in EU, and my AQI sensor shows ~140 which is at almost at the far end of the EU scale (**Very Poor** air quality), but the bagde is orange (**Unhealthy for Sensitive Groups** on the US scale).

Is it possible to add an option for two (or more) scales?
