### ISSUE TITLE
Like to use in 2 time zones - sun2 used for 2nd instance not working

### ISSUE THREAD

**Issue by Tipalo** [pkissling/clock-weather-card#478]
Thanks for this wonderful card.
I've set this as a feature request because it is certainly not a bug.

What I'd like:
Accurate sun/moon icons for 2 time zones. 

Using sun.sun for the local time zone works but using the Sun2 integration for a 2nd time zone does not work with any of it's entities that I've tried..

Need info as to what your sun_entity setting is expecting. Or a way to use the sun2 integration with both time zones.

Thanks for your help.

**Comment by pkissling** [comment]
hi, 
the sun sensor configured via `sun_entity` must expose a state which is `below_horizon` when the sun is below the horizon. that is the only requirement. does this information suffice?

**Comment by Tipalo** [comment]
Yes thanks. I may be able to figure it out from that.
