### ISSUE TITLE
Add an option to prevent the weather details from popping up when clicking the weather icon.

### ISSUE THREAD

**Issue by maodun96** [pkissling/clock-weather-card#481]
**Is your feature request related to a problem? Please describe.**
I use this plugin on a small screen, but I often accidentally tap the weather icon. On a small screen, it's difficult for me to close the pop-up weather details because the close button is too small.

**Describe the solution you'd like**
I would like to have a setting that prevents the weather details from popping up when tapping the weather chart.

**Additional context**
![IMG_4129](https://github.com/user-attachments/assets/060d61b8-4cbf-4035-872a-7afce090511e)

**Comment by pkissling** [comment]
duplicates #117
