### ISSUE TITLE
Update crashes HA

### ISSUE THREAD

**Issue by xylone** [pkissling/clock-weather-card#486]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser
- [X] I read the [FAQ](https://github.com/pkissling/clock-weather-card#faq) and the issue I'm having was not mentioned there.

**Release with the issue:**
2.8.6

**Last working release (if known):**
2.8.5

**Browser and Operating System:**
Safari, HA OS 2024.11.2

**Description of problem:**
I tried to update to the latest version, which looks like it does, except that I'm unable to connect to HA anymore.
After a reboot, everything works fine again and the update of 2.8.6 is back in the update list.
First I thought it was my mistake or a newer version, so tried to update again, but with the same result.
I understand that this is hard to believe, since this is just a frontend update, but I do have a problem with it and there are no other updates or issues.

**Comment by pkissling** [comment]
hi @xylone, can you please provide your HA logs?

**Comment by xylone** [comment]
I already looked. There is nothing there (except from some Type and Value errors from other integrations):

> 2024-11-20 11:11:18.206 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might ca
> use stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.207 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might 
> cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.208 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration stiebel_eltron_isg which has not been tested by Home Assistant. This comp
> onent might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.210 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ovapi which has not been tested by Home Assistant. This component might c
> ause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.211 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration toshiba_ac which has not been tested by Home Assistant. This component mi
> ght cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.212 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration moonraker which has not been tested by Home Assistant. This component mig
> ht cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.213 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component m
> ight cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.214 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration home_connect_alt which has not been tested by Home Assistant. This compon
> ent might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.215 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration battery_sim which has not been tested by Home Assistant. This component m
> ight cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.216 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration knmi which has not been tested by Home Assistant. This component might ca
> use stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.217 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration zonneplan_one which has not been tested by Home Assistant. This component
>  might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.219 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_photos which has not been tested by Home Assistant. This component
>  might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.220 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component mig
> ht cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.222 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration afvalbeheer which has not been tested by Home Assistant. This component m
> ight cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.223 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration switchbot-curtain which has not been tested by Home Assistant. This compo
> nent might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.224 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This comp
> onent might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:18.225 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component mig
> ht cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-11-20 11:11:34.436 ERROR (MainThread) [aiohttp.server] Unhandled exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1254, in _sendfile_fallback
>     read = await self.run_in_executor(None, file.readinto, view)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 560, in start
>     resp, reset = await task
>                   ^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 502, in _handle_request
>     resp, reset = await self.finish_response(request, resp, start_time)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 668, in finish_response
>     await prepare_meth(request)
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_fileresponse.py", line 362, in prepare
>     return await self._sendfile(request, fobj, offset, count)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_fileresponse.py", line 131, in _sendfile
>     await loop.sendfile(transport, fobj, offset, count)
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1233, in sendfile
>     return await self._sendfile_fallback(transport, file,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1263, in _sendfile_fallback
>     await proto.restore()
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 264, in restore
>     self._transport.set_protocol(self._proto)
>   File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 98, in set_protocol
>     self._ssl_protocol._set_app_protocol(protocol)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute '_set_app_protocol'
> 2024-11-20 11:11:34.711 ERROR (MainThread) [aiohttp.server] Unhandled exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1254, in _sendfile_fallback
>     read = await self.run_in_executor(None, file.readinto, view)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 560, in start
>     resp, reset = await task
>                   ^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 502, in _handle_request
>     resp, reset = await self.finish_response(request, resp, start_time)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 668, in finish_response
>     await prepare_meth(request)
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_fileresponse.py", line 362, in prepare
>     return await self._sendfile(request, fobj, offset, count)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_fileresponse.py", line 131, in _sendfile
>     await loop.sendfile(transport, fobj, offset, count)
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1233, in sendfile
>     return await self._sendfile_fallback(transport, file,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1263, in _sendfile_fallback
>     await proto.restore()
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 264, in restore
>     self._transport.set_protocol(self._proto)
>   File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 98, in set_protocol
>     self._ssl_protocol._set_app_protocol(protocol)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute '_set_app_protocol'
> 2024-11-20 11:11:43.070 ERROR (MainThread) [homeassistant.components.mqtt.models] Exception raised while updating state of sensor.duco_ventilation_mode, topic: 'VENTILATION_GATEWAY/VENTILATION_GATEWAY/Ventilationmode' with payload: b'0'
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 659, in state
>     numerical_value = int(value)
>                       ^^^^^^^^^^
> ValueError: invalid literal for int() with base 10: 'Auto'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 662, in state
>     numerical_value = float(value)
>                       ^^^^^^^^^^^^
> ValueError: could not convert string to float: 'Auto'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 366, in process_write_state_requests
>     entity.async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
>     self.__async_calculate_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
>     state = self._stringify_state(available)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
>     if (state := self.state) is None:
>                  ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 666, in state
>     raise ValueError(
> ValueError: Sensor sensor.duco_ventilation_mode has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Auto' (<class 'str'>)
> 2024-11-20 11:11:43.079 ERROR (MainThread) [homeassistant.components.mqtt.models] Exception raised while updating state of sensor.duco_gateway_status, topic: 'VENTILATION_GA
> TEWAY/status/LWT' with payload: b'Connected'
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
>     numerical_value = float(value)  # type:ignore[arg-type]
>

**Comment by xylone** [comment]
Never mind. 
There is something else causing a crash. 
Sorry for sending a bug report. Will close this.
