### ISSUE TITLE
Visualize hourly forecast in same manner

### ISSUE THREAD

**Issue by mvanlijden** [pkissling/clock-weather-card#64]
I am using the TomorrowIO integration to provide met with two entities for forecast, a daily variant and a hourly variant.
The daily variant is working perfectly with this card. When selecting the hourly version, I only get the days bars within the forecast range (based on hours).

Can you also support hourly forecasts, where an hour would be a line?

**Comment by JanGiese** [comment]
Hi @mvanlijden,
I also found it quite useful to display the hourly forecast via this beautiful card, so I have implemented some slight changes, which hopefulle make it into this repository.
[Pull Request](https://github.com/pkissling/clock-weather-card/pull/102)
If you would like to test the adapted version, you can download it [here](https://github.com/JanGiese/clock-weather-card/releases/download/refs%2Fheads%2Frelease/clock-weather-card.js)

**Comment by pkissling** [comment]
Implemented via #102
