### ISSUE TITLE
Time does not update

### ISSUE THREAD

**Issue by Haych** [pkissling/clock-weather-card#8]
Thanks for your custom card, I really like the layout. 

One thing I have noticed though is that the time is not auto updating. On page load it shows the current time at when the page loaded. If I leave that page open though, the time does not update and stays on the same time as when the page loaded. 

I have only tested it on Chrome at this stage.

**Comment by Haych** [comment]
Sorry just to add to this, in the developer console there is this message repeated often: 

clock-weather-card.js?hacstag=522634019101:179 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'state')
    at Ze.shouldUpdate (clock-weather-card.js?hacstag=522634019101:179:206673)
    at Ze.performUpdate (clock-weather-card.js?hacstag=522634019101:25:4896)
    at Ze.scheduleUpdate (clock-weather-card.js?hacstag=522634019101:25:4704)
    at Ze._$EC (clock-weather-card.js?hacstag=522634019101:25:4612)

**Comment by pkissling** [comment]
Glad you like the card and thanks for reporting the issue.
Apparently the card assumes that there is an entity `sensor.time` available. I just realised that the integration is optional and hence not available by default. I will fix this issue.

For the time being, enabling the `time_date` integration (https://www.home-assistant.io/integrations/time_date/) should fix the issue. Can you confirm?

**Comment by pkissling** [comment]
Should be fixed in 1.0.2 release: https://github.com/pkissling/clock-weather-card/releases/tag/1.0.2

**Comment by Haych** [comment]
Thanks mate, it is working in the updated version
