### ISSUE TITLE
iOS12 compatibility

### ISSUE THREAD

**Issue by Camatobe** [pkissling/clock-weather-card#81]
I would love to use this on my wall mounted iPad Air (iOS12)

currently it is not supported:
"Custom element doesn't exist: clock-weather-card"

Deleted Frontend-Cache, Restarted Home-Assistant, restarted the iPad.
Maybe some JS functions wont work on iOS12?

Maybe you can ensure iOS12 compatibility somehow? – when I can provide anything, let me know.

**Comment by pkissling** [comment]
i run the card successfully on different iOS devices. i cannot reproduce the issue.
the error message `Custom element doesn't exist: clock-weather-card` indicates that the card is not properly configured in home assistant.  can you please double check your configuration? https://github.com/pkissling/clock-weather-card#installation-and-tracking-with-hacs

**Comment by Camatobe** [comment]
Checked the configuration twice.
It is properly working on all of my other iOS Devices, Laptops etc.

iOS12-Home-Assistant App is forced to use an older Safari WebKit Version, wich only supports older JS-compatibility (I think it was ES5?)

I guess the iOS Devices you were testing on are iOS13 and above?
The "Custom element doesn't exist: clock-weather-card" - error also appears on custom cards not compatible with this older JS / WebKit Version.

**Comment by pkissling** [comment]
yes, true. i checked on iOS 16. 

gonna try to find the lowest ES version which i can use without changing the code.

**Comment by pkissling** [comment]
with little code changes I was able to downgrade to ES2015.
can you install the manually and give it a spin?

[clock-weather-card.zip](https://github.com/pkissling/clock-weather-card/files/9868105/clock-weather-card.zip)

**Comment by Camatobe** [comment]
Thanks @pkissling ! 
It's definetely a progress!

The card gets recognized. – Weather Icon and Time are visible now, but the Tmp Min-Max-Bars aren't visible tho..

Do you know, how I can view console errors from the home assistant companion webview on iPad? – Maybe I can provide that errors to you.

**Comment by Camatobe** [comment]
Tested it on a separate View, the dot on the current day is missing and bars are moved down attached an unprofessional screenshot 😂![image](https://user-images.githubusercontent.com/51515686/198010120-d74b3dd6-d375-47eb-86ba-bf47d91a3e96.jpeg)

**Comment by pkissling** [comment]
oh wow, great you found it. i don't have an iOS 12 device, hence was not able to reproduce the issue.
so we can merge the code changes and include it in the next release?

**Comment by Camatobe** [comment]
Sounds great! Thanks for the absolutely beautiful work and the fast response! 

In case my changes don't break other stuff (only tested on iOS 12): ship it 🥳 

Maybe some things need tweaking (for example no absolute width for the current indicator. (Use rem instead)

**Comment by pkissling** [comment]
hi @Camatobe 
the following version contains the mentioned css changes.
can you please try this version? if this makes your card work on iOS 12 (without card-mod), then i will include this change in the next release

[clock-weather-card.js.zip](https://github.com/pkissling/clock-weather-card/files/9896044/clock-weather-card.js.zip)

**Comment by Camatobe** [comment]
Looks good so far.
The current day temp indicator dot is still missing tho.

In my modded Version I added `width: 1.5rem;` to this tag:
`<forecast-temperature-bar-current-indicator-dot> `
as the used css `aspect-ratio` is not supported.

I added a screenshot (Modded one on top).
![IMG_0CD936113459-1](https://user-images.githubusercontent.com/51515686/198887170-0fca1074-d8ab-4b65-9ba7-59ff54d5b081.jpeg)

**Comment by pkissling** [comment]
cool, thanks for your help in fixing the issue remotely :D
the following zip now includes all 3 changes:
* dot: `width`
* wrap-top: `text-align`
* clock-weather-card-forecast: `display: block`
[clock-weather-card.js.zip](https://github.com/pkissling/clock-weather-card/files/9896279/clock-weather-card.js.zip)

**Comment by Camatobe** [comment]
tested it, worked like a charm.

Next time, when I have time, I will do the proper way and do a PR ;D Thanks for fixing it!
