### ISSUE TITLE
Where is point?

### ISSUE THREAD

**Issue by dragonerix** [pkissling/clock-weather-card#85]
![Snímek obrazovky 2022-10-27 143628](https://user-images.githubusercontent.com/68662239/198285889-12e86571-b0ee-446e-9129-de4351dc20e0.jpg)
Hi, where is point in BAR graph like you have on main picture https://raw.githubusercontent.com/pkissling/clock-weather-card/1.0.7/.github/assets/card.gif. I not have it.

I have this settings in HA:
type: custom:clock-weather-card
entity: weather.domov
sun_entity: sun.sun
weather_icon_type: line
animated_icon: true
forecast_days: 5
locale: cz
time_format: 24
hide_today_section: false
hide_forecast_section: false

Thank you

**Comment by Shogun1978** [comment]
Same issue here.

**Comment by Camatobe** [comment]
I fixed it, by adding an extra css via card_mod ( https://github.com/thomasloven/lovelace-card-mod ):
```
card_mod:
  style: >
    forecast-temperature-bar-current-indicator-dot {
      width: 1.5rem;
    }
```

maybe your browser does not support the used css-property: https://caniuse.com/mdn-css_properties_aspect-ratio 

this way I was able to ran it on iOS12: 
<img width="503" alt="image" src="https://user-images.githubusercontent.com/51515686/198341772-d75f47c3-c8dd-4421-aa96-56c50b8bc13b.png">

**Comment by pkissling** [comment]
hi @dragonerix, @Shogun1978 is it possible that your issue is related to the issue discussed here?
https://github.com/pkissling/clock-weather-card#why-dont-i-see-the-current-day-in-my-weather-forecast

**Comment by pkissling** [comment]
as an alternative i could calculate calculate today's forecast in the card. but since the weather provider lacks min/max temp for the day, it looks pretty strange. what do you guys think?
![image](https://user-images.githubusercontent.com/33731393/198378082-4cb4c0ab-798c-4ccc-b438-0117ef16674b.png)

**Comment by Shogun1978** [comment]
Indeed, looks quite strange. I didn't manage to ever get OpenWeatherMap up and running, but I will try again today and see if the issue also appears there.

**Comment by Shogun1978** [comment]
Ok, just tested with OpenWeatherMap and the dot is back. Strange...
