### ISSUE TITLE
Date formatting and locale

### ISSUE THREAD

**Issue by stigvi** [pkissling/clock-weather-card#87]
Regarding this, https://github.com/pkissling/clock-weather-card/pull/86 , is it possible to set the same locale as configured with the locale configuration for this card?

**Comment by pkissling** [comment]
sorry, i don't really understand the question. if you set `date_pattern` l, the card will use the configured pattern. if not, it will fall back defined by the default pattern of your language (either `locale`, or if not defined the language set in HA)

**Comment by pkissling** [comment]
what you describe should work properly. can you please provide the expected and the actual pattern? gonna see if i can reproduce the issue with `no` language

**Comment by stigvi** [comment]
![image](https://user-images.githubusercontent.com/25978315/198848586-d4d60f94-bed2-4299-adde-1c1a07e76b53.png)

Lør is ¨norwegian for 'Sat'  so with this version, there is a mix of two different languages

(I used PPPP as an example here. My normal formatting code would be PPP)

**Comment by pkissling** [comment]
i see. my hunch is that the underlying date-fns library does not yet have norwegian language support. gonna have look.

**Comment by stigvi** [comment]
The proper locale code for norwegian is nb and not no. The date is norwegian if I use nb as locale, but then, everything else is in english

**Comment by pkissling** [comment]
nice catch. what do you think about changing supporte locale in the card from `no` to `nb`?

**Comment by stigvi** [comment]
Changing it to nb is the right thing to do, imo. It is a minor change which will solve this little issue.

**Comment by stigvi** [comment]
While you are at it. Could you change Kaos to Storm in the no,json (nb,json) (exceptional = Unwetter = Storm)
