### ISSUE TITLE
Default date formatting

### ISSUE THREAD

**Issue by stigvi** [pkissling/clock-weather-card#89]
As it is possible to format the date (great feature :-) ), is it possible to change the default formatting to "eee, P" and remove the hardcoded weekday at the start of the line?

**Comment by pkissling** [comment]
i initially wanted to do it, but figured that certain languages are not supported in date-fns. with your finding in #87 i realised that for other languages (czech, korean) the ISO 639-1 is wrong, hence translations via date-fns were not working.

i will consider it an enhancement and might implement it in future

**Comment by stigvi** [comment]
What about keep the default as it is now, but if date_pattern has some value configured by the user, then remove the hardcoded weekday?

**Comment by jleach87** [comment]
> There are characters in front of the date pattern.
> 
> ![8CAE2368-5349-4A5F-9AC2-C1F89B7678E7](https://user-images.githubusercontent.com/83040228/199258862-8e57b93f-f210-456a-8fbe-d1c9b28570fc.jpeg)
> 
> ![65FBC13B-1C4E-4964-91FD-619481584C0C](https://user-images.githubusercontent.com/83040228/199258866-635f17f6-0301-4b36-9a28-d7e81302919e.jpeg)

+1

**Comment by alexruffell** [comment]
I believe the issue in this ticket also applies to PPPP as you end up with Thu, Thursday.... as shown below.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/4006944/209214099-02435704-944d-4509-9146-c7d65078d14d.png">

The initial `Thu` should not appear according to date-fns:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/4006944/209214389-208a5201-80fc-407c-b691-fed411588fd4.png">

**Comment by claytonium13** [comment]
I have this same issue.  Is there a workaround to fix the date pattern?

**Comment by alexruffell** [comment]
@claytonium13 I ended up using PPP which just shows short version of the week day. Works perfectly.

**Comment by dolby85** [comment]
same issue here with "PPPP"

**Comment by mycana** [comment]
Same issue here with EEEE MMMM d

**Comment by pkissling** [comment]
fixing this issue would break downwards compatibility, as this might break the card for existing users who rely on the fact that the day is prepended to the date.

i'll add this ticket as a candidate for a new major version (2.0.0)

**Comment by roblatour** [comment]
I would like to see the date format as 
Sunday, May 7th, 2023
and used PPPP as described above and at https://date-fns.org/v2.29.3/docs/format
however what I got was
Sun, Sunday, May 7th, 2023
(with an extra 'Sun,' starting things off)

![image](https://user-images.githubusercontent.com/5200730/236701491-d3bc430f-670d-4a5c-883b-df6a200b43bf.png)

Is this a bug?

**Comment by roblatour** [comment]
I am having the same issue with PPPP
I understand that you are saying 'it would break downwards compatibility, as this might break the card for existing users who rely on the fact that the day is prepended to the date.' however to be fair it is it already not broken for existing users and a fix here would correct it and make it usable by all?

**Comment by m33ts4k0z** [comment]
Hello.

I can't see why is this such an breaking change that would mess the UI but removing this line:

`${this.localize(`day.${e.getDay()}`)}, `

from `clock-weather-card.js` fixed it for me. 

You can use the HA File Editor to edit the file from the web browser. After that you might need to suffix the resources entry with something like `?ver=2` in order to force the webbrowser to reload the file and ignore the cache.

Example:

`/hacsfiles/clock-weather-card/clock-weather-card.js?ver=2`

**Comment by GsynthChris** [comment]
same issue here, just used PPP. definitely not a huge deal.

**Comment by pkissling** [comment]
hey there, i just released a [beta 2.0.0](https://github.com/pkissling/clock-weather-card/releases/tag/2.0.0) which addresses the issue of having a hard coded weekday prepended to the date. please carefully read the changelog. there are other breaking changes, which might require your attention.

i'd appreciate some feedback whether this release solves your problems. cheers

**Comment by alexruffell** [comment]
I installed the beta and all I had to do was replace PPP with DDDD and it is perfect. Thank you!

**Comment by pkissling** [comment]
released 2.0.0

**Comment by Nezz** [comment]
One downside I came across with the Luxon switch is that ordinals are no longer supported. `do` now outputs `<day of the month><day of the year>` instead of ordinal day of the month (i.e. 16th).

**Comment by agnus77** [comment]
I have just updated to v2 and I have "invalid dateTime" using Wunderground forecast.

![image](https://github.com/pkissling/clock-weather-card/assets/79595933/c3706813-5797-4383-b95d-019a3e314191)
I have to set : hourly_forecast: true to show the forsecast


Previous version works fine and Wundergound expose the forecast correctly
![image](https://github.com/pkissling/clock-weather-card/assets/79595933/4fde46e0-38f5-4c39-ae4a-ce9fc5aae39e)

Using another weather service, it works fine.
![image](https://github.com/pkissling/clock-weather-card/assets/79595933/98e134b3-f491-4f5a-ba0b-ae74551c16da)


Someone can helps?

**Comment by pkissling** [comment]
> I have just updated to v2 and I have "invalid dateTime" using Wunderground forecast.
> 
> 
> 
> ![image](https://github.com/pkissling/clock-weather-card/assets/79595933/c3706813-5797-4383-b95d-019a3e314191)
> 
> I have to set : hourly_forecast: true to show the forsecast
> 
> 
> 
> 
> 
> Previous version works fine and Wundergound expose the forecast correctly
> 
> ![image](https://github.com/pkissling/clock-weather-card/assets/79595933/4fde46e0-38f5-4c39-ae4a-ce9fc5aae39e)
> 
> 
> 
> Using another weather service, it works fine.
> 
> ![image](https://github.com/pkissling/clock-weather-card/assets/79595933/98e134b3-f491-4f5a-ba0b-ae74551c16da)
> 
> 
> 
> 
> 
> Someone can helps?

can you call get_forecast service and paste the returned yaml here? i have the feeling that the weather provider uses a different date format than the other weather providers
